### ISSUE TITLE
Feature request: Color/Light temperature

### ISSUE THREAD

**Issue by dobber81** [nielsfaber/scheduler-card#115]
I would love to get the option to choose color for RGB bulbs, and white temperature for the bulbs that support it.

**Comment by nielsfaber** [comment]
If you want a certain color you could define your own action to set it.
But i am not really planning to add a colorpicker and/or color temperature slider to the GUI.
I doubt that there are much users who want to change the color of the lamp based on time of the day (except if we are talking circadian lighting).
What would be your use-case for this?

**Comment by KTibow** [comment]
Could be nice to welcome someone home if they arrive at the same time every day.

**Comment by dobber81** [comment]
> If you want a certain color you could define your own action to set it.
> But i am not really planning to add a colorpicker and/or color temperature slider to the GUI.
> I doubt that there are much users who want to change the color of the lamp based on time of the day (except if we are talking circadian lighting).
> What would be your use-case for this?

I use some bulbs as night-lights all night. Deep red color @5-10% dim. Some other lights are white 80% at 18:00, goes 50% at 20:00 and turns blue or red at 22:00. Blue/red are both less intrusive when people are trying to sleep than white light.
Another reason would be to have red on monday, blue on tuesday, etc.

**Comment by nielsfaber** [comment]
There are a couple reasons why I don't think it should be supported by default in the card:

1. There are very few users who want to change colour of a lamp on a set time
2. The colour setting is very taste depending and implementing a colorpicker like HA uses, will take too much space in the card (both in kilobytes and in visible content)
3. You want to be able to 'tune' the color to your liking, so you would need a 'preview' button in the card to see what your chosen color looks like. This is not in place.
4. Defining color and brightness as variables for your action, will mean that you have to set 2 parameters. Currently an action only can have one variable. It requires extra effort to accommodate this and may be confusing for users.

I would propose to create customisation for this.
Something like this:
```
customize:
  light.my_colored_lamp:
    actions:
      - name: "turn on with red color"
        service: turn_on
        service_data:
          rgb_color: [255,0,0]
        variable:
          field: brightness
          min: 0
          max: 255
          unit: '%'
```
Perhaps the whole `variable` declaration could be even omitted, since the card should detect whether the lamp is dimmable and add the brightness slider if so. I'm not sure it this would work.

**Comment by KTibow** [comment]
Check light-entity card for an example.

**Comment by dobber81** [comment]
A customization would be ok I guess. Just as long as I'm able to switch colors by specific times I'm happy. Once set I rarely change colors in the schedule for a specific light.

**Comment by nielsfaber** [comment]
@dobber81 did you try adding your own customisation (using the code I shared)?
adding a colorpicker to the card is not really a priority right now, so I rather help you get the functionality you want.

**Comment by dobber81** [comment]
> @dobber81 did you try adding your own customisation (using the code I shared)?
> adding a colorpicker to the card is not really a priority right now, so I rather help you get the functionality you want.

It works! I did have too keep the "variable" part for dim level to be set. But this is perfectly alright until you get the time and/or need to add a color wheel or similar.

Great addon!

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
