### ISSUE TITLE
Make schema explanation

### ISSUE THREAD

**Issue by GianCann** [nielsfaber/scheduler-card#156]
I try to undestand better the "Make schema" option:
![Screenshot_20201021_072504_io homeassistant companion android](https://user-images.githubusercontent.com/45897944/96677190-5eefbf00-136f-11eb-8d90-3c9193d25937.jpg)
I try this schema. The light turn on at start time, but not tun off at end time.

I need to add a second range with 'Turn off'?

A little note: it's very impossible to manage short interval, specially from the smartphone.

**Comment by nielsfaber** [comment]
> I need to add a second range with 'Turn off'?

Yes. The scheduler cannot 'know' what you want for the rest of the day..

> A little note: it's very impossible to manage short interval, specially from the smartphone.

I know. 
But I don't have any way to improve this.
Better to use your phone horizotnally.

**Comment by GianCann** [comment]
> Yes. The scheduler cannot 'know' what you want for the rest of the day.

I think that the scheduler could be restore the state of entity before the start time of a slot.

I don't find the sense of setting a "end time" if nothing happen when the time is reached.

**Comment by nielsfaber** [comment]
I understand your point.
And in your case it is very clear.
But for other schedules (for example climate), it will be hard to determine what the user wants when the timeslot finished.
I would rather add the option to enter a start and end action for each timeslot, instead of 'assuming' what needs to be done.

But there are many improvements still 😄
