### ISSUE TITLE
Climate cool/heat temperature step size

### ISSUE THREAD

**Issue by mottibz** [nielsfaber/scheduler-card#157]
Hi, I noticed that now when selecting cool/heat action for a climate device, the slider for selecting the temperature is working in 0.5 degree steps. How can I change to 1 degree steps? Thanks!

**Comment by mottibz** [comment]
Hi, I see that you closed this item. Can you tell me how to support the above 1 degree steps instead of 0.5 which is currently being used (1 degree steps is documented as the default)? Thanks!

**Comment by nielsfaber** [comment]
Its closed because github is meant for reporting issues (bugs) or feature requests.
This is not the first time I am telling you this.
Use the forum for assistance on how to set up the card.
And read the documentation.

In this case, you will have to define your own custom action, because you want it customized..
