### ISSUE TITLE
Another major release?

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#222]
It might be time for 2.0.0 soon, or sometime.

**Comment by nielsfaber** [comment]
How do you mean?
I would say that there should be a major change first no?

**Comment by KTibow** [comment]
You're right, but once this hits the `1.10`s it starts to get ridiculous.

**Comment by dj4ngo** [comment]
I hope no; I hope we won't go for a major version without a good reason. 

My feeling is that following semver is really more valuable for the project :

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

Here is more documentations on how semver is working : https://semver.org/

A change like moving to websocket api for communication between card and component could typically be a candidate to perform this jump.

**Comment by nielsfaber** [comment]
Exactly.
I only increase the middle digit when I expect breaking changes.
No reason for increasing the left digit..
The numbering is not meant to look pretty.

I don't really want to argue on these matters. 
Its my own choice how to deal with updates...
After all this is just a hobby project.

I'm closing this because I don't see a need for discussing it more.
