### ISSUE TITLE
Action with Condition

### ISSUE THREAD

**Issue by reesion** [nielsfaber/scheduler-card#24]
Hi, 

is it possible to have a condition for an action ? Like if the Thermostat is below 15 degrees at 6am turn on the heater?

**Comment by nielsfaber** [comment]
It is not supported currently, no.
It is also not really planned, because it will add quite some extra buttons and fields to the GUI, which might get confusing.
But it could be considered if it helps a lot.

For now, if you want to do something like this, you could create a script/automation that has the condition.
This script/automation can be triggered as a schedule.
You could pass the temperature threshold condition as a variable from the card, so no hard-coded level.

**Comment by reesion** [comment]
Ok thanks for confirming.
 If would be helpful if the features are available as it reduces the need to write manual scripts and automations.

**Comment by KTibow** [comment]
Personally, I think it's really easy to make an automation with the GUI, the main reason I use this component is because it's a bit faster.
I think that it's better to have no condition format then a limited condition format, because I don't see the point of recreating Home Assistant's advanced condition system when it'll just lead to lots of bugs.
Sure, I'm be being lazy and not seeing the point, but I think that it's pretty easy to maybe just add a quick link at the bottom to create a new script.

**Comment by EnryDalo** [comment]
Thank you very much for your work, the card is very easy to use and surely the best scheduler available for HA so far. 
I think it's a must to include some conditional starting. For example, i would like to progam a climate shedule like the TADO application and would like to include the "at home/away" detection. This is impossible to make without a conditional checking, you could just add a simple one.

**Comment by nielsfaber** [comment]
@EnryDalo adding such functionality is not considered at this point. 
There are two alternatives:

1.  Use the scheduler to trigger a `script` that contains the condition and action. It is possible to pass a variable (such as temperature setpoint) to the script.
2. Use an `automation` to check the condition and turn off the schedule when it should not do anything.  There is an open request for giving schedules a better name / entity_id, which should facilitate this.

**Comment by mycanaletto** [comment]
+1

**Comment by KTibow** [comment]
@mycanaletto please hit the +1 emoji so that people can sort by most positive reactions as well.

**Comment by nielsfaber** [comment]
Suggestion of @MatteGary (I post it here because it is a related FR):

> It would be awesome to have the possibility to let an automation run if no one is at home, or if someone is at home, like Apple Home App let us do.
I have an automation in Apple Home App that basically is “If no one is at home at 19:00, then turn on my garden light”.
Option should be:
. Run if no one is at home
. Run if someone is at home

**Comment by nielsfaber** [comment]
Conditions are introduced in v1.7.5 so you should be able to make the behavior as you wanted it.
Note that (currently) you cannot set up a condition in combination with an entity attribute, only the state will be checked.
So if you want to use the temperature of a climate entity, you should add a template sensor for this.
Please test this new functionality!

**Comment by KTibow** [comment]
A bit more margin between the icon and the text is needed:
![image](https://user-images.githubusercontent.com/10727862/95656375-c0d43d00-0ac2-11eb-8bcb-af4c79190d52.png)
Also, I think the confirm button:
![image](https://user-images.githubusercontent.com/10727862/95656383-d8132a80-0ac2-11eb-93cf-428e373007a4.png)
Should probably be the same as:
![image](https://user-images.githubusercontent.com/10727862/95656385-e2cdbf80-0ac2-11eb-88d4-fa696d2769d0.png)
Any docs about this?

**Comment by nielsfaber** [comment]
Closing since this is in place now.
If there is more functionality needed regarding conditions, please let me know! (open new FR for it please).
