### ISSUE TITLE
Above/below numeric state conditions

### ISSUE THREAD

**Issue by EKCJ** [nielsfaber/scheduler-card#248]
I notice the docs say that conditions can use above/below checks for sensors with numeric states - how do I access this?

I have added my sensor in customize, with the following config:
```customize:
  sensor.bedroom_curtemp:
    states:
      min: 0
      max: 40
      step: 0.5
      unit: '°C'
```

In the condition UI I see this:
![image](https://user-images.githubusercontent.com/67192679/101993397-3b336000-3cb2-11eb-9980-8b714e0b04aa.png)

Intuitively I clicked "IS" to try to change it to "BELOW" but it just goes blank, and clicking it again changes it back to "IS".

Am I doing this wrong or is it not working as intended?

**Comment by nielsfaber** [comment]
I admit that the implementation is a bit buggy.
There is a new version on the way that should solve these problems.

The idea is that for numeric entities, you will get a text field where you can enter the value to compare to, and you have options BELOW / ABOVE for the comparison.
For other entity types (on/off type) you get IS or IS_NOT as compare type.

The `states` configuration will be dropped, because it is not nice to work with.
I am hoping to make this release by tomorrow, but it also comes with a (breaking) release of the scheduler-component.

Until then, I'm afraid the conditions are very limited.

**Comment by EKCJ** [comment]
Thanks, that's helpful. I'll keep my existing automations for this device and look forward to the new release. 🙂
