### ISSUE TITLE
Thermostat temperature time slot

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#268]
To take again ideas that I put in the forum, I think that for the thermostats it would be interesting to do this in the schedule by time slot:

- define a base temperature (eco)
- in a time slot, adjust a new temperature and at the end return automatically to the base temperature.

Other solution or complement :
- schedule a start time temp and slot time stop action

**Comment by nielsfaber** [comment]
I would like to keep the scheduler integration generic. 
So I am not planning to add specific intelligence for dealing with climate entities. 
In other words: adding extra functionality will only be considered if it would be helpful for other entities too. If not, it is too specific to be added, and I rather keep the responsibility at the user.

Therefor, I see two options to implement your request:
1. After the (last) timeslot ends, revert the entity to the state before the (first) timeslot.
 As I mentioned on the forums, I see some issues with this since for some entities, changing the state is not that straight forward. For climate entities for example, we should take into account: temperature setpoint, hvac_mode, preset_mode, (end perhaps others).
Additional consideration here: the state prior to the first timeslot, could also be (manually) set by the user. In such case, it may not be desirable to always revert to this state.
2. Allowing the user to define start+stop actions. I think this is a good improvement, that will help a lot of people. The timeslot editor is not practical for creating a very short slot (as final action). 
I am looking ideas how to incorporate this in the GUI. It should be very clear for the user, so it is not desirable to add a lot of extra fields in the GUI. 
Ideally I would like to combine the timeslot editor with the 'simple' editor. The starting point would be a single action, and it could be extended with additional actions (I think a single timeslot with start+stop action is quite common).
If you have any ideas on how to change the layout for this, please share.

**Comment by mycanaletto** [comment]
I understand your point of view of keeping something generic rather than "climate" oriented.

That's why I had talked about option 2 which seems logical and adapted to any use.

As far as the presentation is concerned, I think it is enough to double the slider (if we assume that the type of action at the beginning is the same as the one at the end, which remains a choice to be defined, but could be a starting choice).

**Comment by nielsfaber** [comment]
I am currently working on reorganising the layout.
Figuring out if and how I could take this into account.

**Comment by mycanaletto** [comment]
Good news, a lot of people have confirmed to me that the idea of a start action and an end action would be a real improvement.

The other idea of defining a default option for a piece of equipment might be more interesting. For example, by default, OFF for a switch or a temperature for a thermostat, and thus define only the start action of the slot. This is how Schedy works.
