### ISSUE TITLE
[Question] How to change the name of an entry?

### ISSUE THREAD

**Issue by wsw70** [nielsfaber/scheduler-card#275]
To start with: thank you for this awesome card. i have all my scheduling in `pyscript` automations but I think I will switch them to this :)

One thing I could not find is how to change the default name of an action:

![image](https://user-images.githubusercontent.com/1345886/103378801-e1210000-4ae3-11eb-9aab-8924b1050708.png)

I did change the friendly name, but it is not the one displayed. The friendly name is visible in entities, though.

Is there a way to change that?

**Comment by RentreX** [comment]
In the code editor of the card you have to put in

display_options:
  primary_info:
    - name

Example:

type: 'custom:scheduler-card'
display_options:
  primary_info:
    - name
groups:
  - name: Lighting
    icon: ceiling-light
    include:
      - light

**Comment by KTibow** [comment]
@RentreX That's how to only display the name. @wsw70 wants to change the name to something else. I believe you'll find it by clicking on options/advanced.

**Comment by nielsfaber** [comment]
@wsw70  the "3x couvertures" part is not customizable. This format is used (instead of the full friendly-names of all entities) to keep the entity name short.
As @RentreX says, it is possible to give a schedule a name and display that instead of the entity: action format. But this configuration applies to the whole card, not per schedule.

**Comment by wsw70** [comment]
@nielsfaber 

> the "3x couvertures" part is not customizable.

But in the demonstration video, there are entries called "Garden Lights" or "Bedroom Curtains" (then, below in a stack there is the action and the time). My "3x couvertures: Ajuster la position à 25%" couldn't in the same way be changed to something like "All covers"?

*BTW: I did a pull request for the French translation, among others because that "couverture" I saw in my tests is a blanket (the one you put on a bed), probably because "couverture" can mean "cover" in English, but in the sense of a cover an infiltrated FBI agent for instance.*

**Comment by nielsfaber** [comment]
Selecting multiple entities is only possible since the last version release.
There is no functionality for assigning a custom name to the selection.
If you want this, you could consider to create a group.all_covers entity.

The schedules used in the demonstration all consist of single entities. Garden lights is a light group. The bedroom curtains are on a single motorized rail.

The translations are meant to be maintained/improved by the users, so it’s appreciated if you create PRs for changes (as you did). I don’t know why the other maintainer chose this name, it seems like you gave it more thought than he did 👍

**Comment by wsw70** [comment]
> If you want this, you could consider to create a group.all_covers entity.

Thank you for following up . I actually have a single entity for all covers. How would I do to rename it? I am not clear from @RentreX example where it fits.

> The translations are meant to be maintained/improved by the users,

Happy to contribute. The original translator made a great job, I just added minor changes.

**Comment by nielsfaber** [comment]
If you have a single entity I recommend to use that one instead.
The card allows you to overwrite the friendly name of the entity through `customize`.
Note that it is a yaml-only feature.
See [here](https://github.com/nielsfaber/scheduler-card#actions) for an example (using my dining lights) on how to use it.
Consider closing this issue if it answers your question.

**Comment by wsw70** [comment]
Thank you, I finally understood how to change the name. 

As a suggestion, it would be awesome to be able to rename someday a set of entities (like my `3x couvertures`) instead of creating a specific group for them.

Thanks for the help!
