### ISSUE TITLE
Synchronizing state between card and schedule entity

### ISSUE THREAD

**Issue by gejr** [nielsfaber/scheduler-card#28]
When I run the switch.turn_off service on one of the switch.schedule_--- entities it seems that it is still shown as on according to the card. Is there a way to have the card reflect that the schedule is off? The state of the schedule goes from "waiting" to "off" as expected.

Eagerly following your progress on this scheduler. Great work so far!

**Comment by nielsfaber** [comment]
When a scheduler entity (eg `switch.schedule_123456`) is disabled, this should be visible in the card.
In the overview of schedules you should see a switch in the ‘off’ position, and the text should be greyed out. 
If this isn’t the case for you then maybe you are dealing with some bug.
Let me know if you have different behaviour.

**Comment by KTibow** [comment]
Just curious @nielsfaber does the card receive real-time updates via the `hass` object?

**Comment by gejr** [comment]
> When a scheduler entity (eg `switch.schedule_123456`) is disabled, this should be visible in the card.
> In the overview of schedules you should see a switch in the ‘off’ position, and the text should be greyed out.
> If this isn’t the case for you then maybe you are dealing with some bug.
> Let me know if you have different behaviour.

Yes, this is exactly what I would expect too. Not working as is. Let me know if there is anything I can do to help debug.

Scheduler component version 2.0.0
Scheduler card  version 1.2.7

I have only made two very simple schedules so far. Only one card visible which shows the two. If I click on the switches it toggles the state between "waiting" and "off" as expected. But manually running the switch.turn_on / turn_off does nothing to the state of the toggle switch on the card. It seems to be a strictly visual bug though, as the state of the schedules turns on/off as expected.

**Comment by nielsfaber** [comment]
Ah now I get it.
The card does not check for updates in the HA schedule entities continuously, only when it is expected (so after changing something through the card).
Turning off a schedule externally indeed is not shown in the card, you will have to refresh the Lovelace view before you see the change.
Good catch!
The bug is as you said purely cosmetic, but I will try to improve the response.

**Comment by Misiu** [comment]
@nielsfaber maybe this can be done via WebSockets?
Not sure if this is possible in custom integrations, but Dynalite is adding that, so I guess it can be done 🙂
https://github.com/home-assistant/core/pull/38948
https://github.com/home-assistant/frontend/pull/6635

**Comment by nielsfaber** [comment]
@Misiu It’s actually already in place.
Currently I get an update from HA every time an entity changes.
I added quite strict filtering to avoid the card from reloading all schedules every X seconds (which was really the case in my own HA setup due to sensor entities that get frequent readings).
I could refresh the view when something happens (externally) with any scheduler entity.
Please allow me some time to fix it properly.

**Comment by nielsfaber** [comment]
This should be fixed by updating to [v1.4.2](https://github.com/nielsfaber/scheduler-card/releases).
Please test if it solves the problem for you, and close the issue if so.

**Comment by KTibow** [comment]
@nielsfaber consider installing the @stalebot bot.

**Comment by nielsfaber** [comment]
I close this issue, assuming it is fixed. Let me know if you still have problems.
