### ISSUE TITLE
Feature request: At the latest / earliest

### ISSUE THREAD

**Issue by KNXBroker** [nielsfaber/scheduler-card#281]
Hello, happy new year! Great card / component. Thank you!

I would like to do the following: 

In the morning my covers shall open at SunRise, but not before a specific time (e.g. 07.00). Having this feature in the scheduler would be fantastic.  Could you think of adding an optional feature, which allows to execute actions at the latest or earliest?

Looking forward for your comments. Best regards

**Comment by nielsfaber** [comment]
Unfortunately there is no easy way to accomplish this.

One way I can think, is by creating a template binary_sensor that is ON after 07:00.
The card already allows you to add such condition to a schedule.
It would be prettier if you could use a time sensor directly and compare with this time, but there is no support for creating conditions with time input.

If you add this condition to a schedule that triggers at sunrise, the effect would be that the schedule would be skipped if sunrise is before 07:00.
You would need to create a second schedule that triggers at 07:00 as alternative action.

Since this method is a bit hacky, I'm not sure if this is what you're looking for.
Maybe it's easier to switch twice per year between sunrise controlled and fixed time.
Where I live sunrise is before 07:00 from around half March to half September.

I'm not planning to add new functionality to accommodate this function.
IMO it would add quite some complexity to the GUI, and I doubt many people would use it..

**Comment by KNXBroker** [comment]
Thank you for your feedback. I can fully understand that you don't want to add too complex functionalities, especially if I see the 'issue' list. But on the other side this shows, how important and good your scheduler is. It offers a lots of new possibilites.

I'm still thinking how to solve it... let's see. It's not only in the morning, it's in the evening as well (e.g. covers shall be closed at 8.00pm at the very latest). In addition schedules shall be different for every room, which makes it even more difficult. 

If I find a smart solution I will post it here, I'm thinking of combing your scheduler with a blueprint. Best regards.

**Comment by nielsfaber** [comment]
I think the best way to solve this is by:
1. Giving the ability to add a time in a condition
2. Create the option to have a schedule 're-evaluated' when the conditions are met.

This way the GUI can be kept more-or-less as is.
Both added functions can be generically usable:
* I received quite some request of people who only want to have a schedule run for certain period (like christmas lights or winter garden lights etc.)
* Also I received the request from users who would like to add a window sensor in a condition for a thermostat climate, to have it turned off while the window is closed and automatically turned on when you close the window

The problem is that both functions will take quite some time and effort to make...
