### ISSUE TITLE
Standard menu are gone - Ver. 2.0.3

### ISSUE THREAD

**Issue by fiorentino77** [nielsfaber/scheduler-card#290]
After last update it seems the standard menu are gone.
Chrome dev tools:

![Cattura](https://user-images.githubusercontent.com/56383979/103489168-b64fe800-4e12-11eb-9fb6-71150926fb82.PNG)

Other thing.
I've made a schedule with binary sensor (as hysteresis) and input.boolean (about colf presence) but in Hassio Dev Tools no conditions are shown:

![Cattura2](https://user-images.githubusercontent.com/56383979/103489147-9b7d7380-4e12-11eb-9825-9856c8af2a3a.PNG)
![Cattura3](https://user-images.githubusercontent.com/56383979/103489154-9f10fa80-4e12-11eb-810c-5c58accf996b.PNG)

Thanks in advance.
Regards,

Alessandro

**Comment by nielsfaber** [comment]
> After last update it seems the standard menu are gone.
Chrome dev tools:

This seems to be caused by a `group` entity in your config, for which the card cannot calculate the entity states.
Do you maybe have some empty group or one with old entities that don't exist?

> I've made a schedule with binary sensor (as hysteresis) and input.boolean (about colf presence) but in Hassio Dev Tools no conditions are shown:

Conditions are not shown as attributes of the entities currently.
I could add this though..

**Comment by fiorentino77** [comment]
Fixed with ver. 2.0.4.
Thanks!
