### ISSUE TITLE
[BUG] Stops preforming a scheme when "behavior after triggering" sets to "stop"

### ISSUE THREAD

**Issue by SSilvering** [nielsfaber/scheduler-card#310]
When I set a schedule with scheme and set "behavior after triggering" to "stop", it stops the specific schedule after activating the first action of the scheme and it does not perform the other actions in the scheme.
The desired result is that it will stops the program after performing the entire scheme, or I  #misunderstood it right. 
I work with the latest versions of the card and the component.

**Comment by nielsfaber** [comment]
Seems that you misunderstood the behavior.
The first timeslot will be executed only.
This is not a bug, the feature is intended for using with non-timescheme tasks.
The scheduler does not keep a counter or anything to check that all slots have been executed once.
This is not even possible, since you could restart HA in the process.

**Comment by SSilvering** [comment]
ok I see. thank you for you great work.
