### ISSUE TITLE
Automation not appearing in list

### ISSUE THREAD

**Issue by crixster** [nielsfaber/scheduler-card#311]
I have included it in card configuration
![image](https://user-images.githubusercontent.com/32066057/105149924-0f23be00-5b3f-11eb-9247-a3ef2363ef82.png)

but it still doesn't appear in the card
![image](https://user-images.githubusercontent.com/32066057/105150110-4e520f00-5b3f-11eb-8222-c1ab9f701d0b.png)

I'm pretty new to all this so i apologize for any mistakes

**Comment by nielsfaber** [comment]
Hello,
For automations the card doesn’t offer any built-in actions.
This is because automations work with their own triggers. 
The card can only enable/disable an automation, but it won’t trigger any actions directly.
If this is what you want, you can define your own actions using [customize](https://github.com/nielsfaber/scheduler-card#actions).

**Comment by nielsfaber** [comment]
Discussion can be continued in https://github.com/nielsfaber/scheduler-card/issues/312
