### ISSUE TITLE
Dawn/Dusk

### ISSUE THREAD

**Issue by TTLucian** [nielsfaber/scheduler-card#320]
Is it (or would it be) possible to use dawn/dusk instead of sunset/sunrise?

**Comment by nielsfaber** [comment]
I chose not to add this to the scheduler, since it would require a more complicated GUI.
Instead you can choose sunrise/sunset with offset, it would give exactly the same effect.
I.e. dawn = 70 mins before sunrise, dusk = 70 mins after sunset (depends a little bit on where you live)

**Comment by TTLucian** [comment]
That's a bummer! 😞 Actually, the time between dawn - sunset / dusk - sunrise (civil twilight) also varies with the season. If you live far enough north or south, the duration varies quite a lot throughout the year. In Amsterdam, for example, civil twilight lasts approximately 1 hour in March and September and 1:40 h in June (morning + evening). So the dusk/dawn approach would be more useful for lights scheduling since it refers to the actual light level outside as the civil twilight refers to the period when enough natural light remains that artificial light is not needed.
Thanks again! 👍

**Comment by hubikj** [comment]
Hello,

Would the GUI really be that complicated by adding two more icons for dawn and dusk in these two places?
![image](https://user-images.githubusercontent.com/9319842/149038712-9b95dd8d-11be-419a-8b04-4e5c80f77b52.png)
![image](https://user-images.githubusercontent.com/9319842/149038753-3d06c20e-4d38-4e5b-a76d-a58e7a2ae01d.png)
I think that in the single time schedule (second picture), it would also be beneficial to have the text names displayed the same way as in the schemes, because it looks much clearer than just icon. I remember being confused by the look of the icons in the single time schedule when I created my first.

I was looking through the icons available in HA and I think you could use these, but it is obviously up to you:
Dawn: mdi:weather-sunny-off (I am not sure about this one)
Sunrise: mdi:weather-sunset-up
Sunset: mdi:weather-sunset-down
Dusk: mdi:weather-night

Especially dusk would be very useful for me for scheduling blinds and lights. I live in central Europe and the times differ greatly between winter and summer, so I have to constantly adjust the sunset offsets as it is now.

Thank you for this amazing project!
