### ISSUE TITLE
Add ability to disable timeslot execution on hass restart

### ISSUE THREAD

**Issue by odya** [nielsfaber/scheduler-card#332]
Current scheduler behaviour looks great when we use it not for controlling stateful entities (like heaters or lights). 
But it becomes confusing when you trying to automate something stateless (e.g. cat feeder, watering plants). 

I think it would be great to have ability to control timeslot execution on hass restart via some parameter.

**Comment by nielsfaber** [comment]
The behaviour you're describing is part of the timeslot concept: it works over a period rather than a single time instance.
I suggest you to just make the timeslot shorter if you don't want it to (re)trigger any action during the whole period.
As far as I know, there is no such thing as a stateless entity in HA. Could you clarify?
Your request seems to cover a rather specific use-case, I'm not sure if the scheduler needs such functionality.

**Comment by KTibow** [comment]
> As far as I know, there is no such thing as a stateless entity in HA.

Yes, but you could create an entity with a never-changing state.

> I'm not sure if the scheduler needs such functionality.

Personally, I agree.
