### ISSUE TITLE
card with only some schedules

### ISSUE THREAD

**Issue by IsaacBreuer** [nielsfaber/scheduler-card#353]
I have alot of schedules based on conditions on the same entities,  so it all gets added to same card even discover existing is off, as its the same domain (and entity), but would love to organize them based on my own stuff, so would be option to add card and only add certain existing schedules? 
let me explain.

I use conditions based of different holidays  each holiday has time on and off, (the holidays is used in conditions) and each holiday has couple schedules, so I would like to have each holiday on separate cars.

and also setting the order of schedules in the card

**Comment by KTibow** [comment]
This seems pretty valid, but as for

> and also setting the order of schedules in the card

This has been numerously denied by @nielsfaber; see #306, #13, and #2.

**Comment by bikeymouse** [comment]
I just put in a feature request, which would basically solve this. 

Not so much to have multiple cards, but to have a "filter"/activation of schedules based on if it is a Holliday (or whatever you want to call the organization of a set of schedules). I call these "timer plans". See  [this issue](https://github.com/nielsfaber/scheduler-card/issues/357).

**Comment by nielsfaber** [comment]
I think this is a fair request.
I don't recall rejecting such request before, the requests referred by @KTibow where related to sorting rather than filtering.
Let's use this issue to discuss which kind of filtering would be useful.

Currently filtering is only possible by entity: you can put all your climate schedules separate from light schedules etc, simply by means of `include`/`exclude` rules.

Additional filtering options (such as holiday schedules) might be difficult, since the scheduler-card cannot distinguish which schedules you would like to see together (with the exception of filtering by weekdays).
The best way forward (IMHO) is to assign each scheduler-card in your Lovelace setup with some unique tag/property/id.
Any schedules created by this card will then be assigned with this tag.
They will also automatically only show up in a card with having this tag, so they will stay where you created them.

However: it gets problematic if a user decides to change/remove the tag later on (or the card altogether).
In this case, all schedules carrying this tag would become invisible to the user, as they don't show up in the Lovelace UI anymore.
It is also rather impossible for a scheduler-card to be aware of other instances of the card, and implement a 'discovery' mechanism to show which ones are not included by any card.

Anyone who has any ideas that would help overcome this issue, or another strategy for the filtering, please share.

**Comment by bikeymouse** [comment]
As I [suggested](https://github.com/nielsfaber/scheduler-card/issues/337) perhaps a solution would be not to filter on tags, but on a boolean entity (which could be "workingday" but also anything else). That would solve the 'discovery' issue.
That could be implemented by adding that as a "filter" to the custom yaml.
Even if the boolean entity would be removed at some time, by removing that rule, all schedules that where hidden will show up again on the card.

**Comment by IsaacBreuer** [comment]
why not a tag as nielsfbar suggest, and have tag editable same as we now
have name editable,  and also have the tag as part of yaml,  as far as
orphan schedules, I whould suggest that this filtering only work if
discovery is false, .. so once we have a card with discovery true we will
be able to see all all schedules.

**Comment by bikeymouse** [comment]
The advantage of using a boolean entity, instead of a tag, is that it would make the filter dynamic. E.g. it could only show schedules of for which the boolean helper entity "vacation-schedules" would be "true".

**Comment by IsaacBreuer** [comment]
but if you want to see the schedules ahead of time when the vacation
boolean and or holiday is not yet true, . tags whould allow you to
customize and see your entire year, while boolean whould be nice to show
current events, which is not the same thing at all.

**Comment by bikeymouse** [comment]
If you use an input boolean helper entity you can just set it to the value to show al entries. 

So you can use this just like a tag, but in contrast, can use it for more dynamic filtering.

By using the helper also as condition in the schedules you would have dynamic filtering AND activation at the same time.

**Comment by nielsfaber** [comment]
@bikeymouse Could you explain your idea with an input_boolean?
How/where would this be visible in the card, and in what way would it provide filtering ability?
I cannot really follow your idea so far (but that happens a lot 😇 )

**Comment by bikeymouse** [comment]
Ok I tried to visualize it.

First there should be some way to configure which "timer plans" (e.g. an input_boolean, but any other boolean entity could be used) can be used to assign to schedules. 

And then, when you create a Scheduler card you would have to able to indicate which active time plans it should show.

If you would combine this at card level-customization, it could look like this:

![timer_plan_custom_card](https://user-images.githubusercontent.com/34967010/113475132-040cd880-9474-11eb-8316-3fa3407a8036.png)

So here is defined that it is possible to assign a timer schedule to 2 timer-plans. And secondly, that this specific card should only show schedules that are assigned to be active based on the "binary_sensor. workday_sensor".

(If no timer_plans are defined the current working should be used: i.e. no filtering and no activation based on a boolean sensor).

Now that the Schedular card knows what which booleans can be used as "timer-plan" and which ones to use for filtering, you can when creating a new schedule for an entity, at a point in the process, assign that schedule to one or more timer plans:

![Create_schedule](https://user-images.githubusercontent.com/34967010/113475707-8a76e980-9477-11eb-9fac-0ce886ce2e0d.png)

Now after creating this schedule and assigning it only to the "Holliday" timer-plan, it would only show up on all the cards that would have the "binary_sensor. workday_sensor" set in the "visible_timerplans"  section. So the filtering is not based on if the boolean is actually "on" but only if the schedule is assigned to that boolean. So that's the filtering part. 
But for the activation part, it basically would also have to work as an additional condition.

As for the example of the topic-starter: he could create a couple of input_booleans for different Holliday's he wishes to show on different cards. Then he could define in the card configuration which hollidays should be visible for each card. So he could create separate cards for separate Holliday's. Or combine a couple of Holliday's on one card.

And when creating a schedule can assign that schedule to one or more Holliday's without having to "dive" into the Conditions details.

**Comment by IsaacBreuer** [comment]
What the benefit of having other boolean entities involved as opposed to
just tags, so we don't have to create additional helpers?

**Comment by bikeymouse** [comment]
It is just the other way around, if you would use tag’s you still would need to create Booleans to use in the conditions 😂. 

So in your case you would use the Booleans you allready use in your Holliday schedule’s, but now could use these to filter/organise your cards as well. And you wouldn’t have to put these in the details of the conditions, just “assign” it to the schedule like shown in the picture.

To be clear the “timerplans” would work both as a way to filter schedules but also as a “master” condition.

The advantage of a Boolean over a tag is that it can be controlled in automations as well as in the GUI. 

The simplest example would be the weekdays Boolean, but in my case I would like to have e.g. an “Even-Week” Boolean.
Now I’m using that in conditions in schedules  but that is burried in the details of these schedules with no way to organize that on different cards.

**Comment by IsaacBreuer** [comment]
I see, but currently I an unsung conditions from a impute select (not
boolean ) and am I am able to select the conditions from gui very easily,
(I created automation to update the select based on holiday schedule ) so I
use multiple holidays sometimes as  conditions (with any settings )

**Comment by bikeymouse** [comment]
You could use the automation that updates the select, to update the boolean as well (and vice versa).

Btw: I'm coming from Domoticz where this concept of timer plan's is already implemented, there is is using an input select to choose the timer plan, ha, ha. And you can use this select in automations as well to set it. 
So if it would be implemented the same way I would be happy too😎

**Comment by nielsfaber** [comment]
Let's please not mix up the functionality of assigning **conditions** to schedules with the **filtering function** that is under discussion here:

- Conditions are used by the scheduler-component to determine whether the actions need to be executed or skipped.
- The **filtering function** will only be added for display purposes in the card, and they will not have any impact on the execution of timers.

So far the concept I have in mind is as follows:

1.  A schedule can be assigned with one or more tags.
2. These tags will become accessible in the card (probably in the options tab), you will have the option to add/remove them when creating/editing a schedule.
3. On the card level you will get the ability to choose which tags you want to filter. By default all tags will be included. It will be the responsibility of the user to use tags here that match with the ones assigned to schedules.
4. On the card level you will get the ability to assign a 'default tag' for schedules, such that when you create a new schedule, it will get a tag that matches with the card (i.e. it will 'belong' to that card). This makes step 2 an optional step, mostly for moving/modifying schedules.
5. The user will have the option of diplaying tags in the overview page (similar to the GitHub issues list), to help identifying schedules.

I consider steps 2+5 optional/extra steps which may not be initially needed.. There's always a downside that added functionality will make the GUI more complicated.
For a simpleimplementation, the option of assigning 1 tag per card (and having it assigned to each schedule of that card) should be sufficient.
It would solve the "holiday schedules apart" use-case as well as the "weekend separate from weekday" use-case.

So far I don't feel much for involving helper (boolean) entities for the filtering function. I don't see the point of having the filtering function change based on states of these switches, IMO it will be more transparent if a tag is a static property of a schedule+card.

**Comment by IsaacBreuer** [comment]
I know I could update the boolean from automation,  but then it's going to
get complicated having multiple conditions  that u can now do in the
scheduler  card gui,

**Comment by IsaacBreuer** [comment]
Yes , I like that approach nielsfaber

**Comment by bikeymouse** [comment]
The proposed working  with the tag’s looks nice and simple, it would surely help al lot to organize the schedules. So 👍

Still I think that in practice this will always be combined with an entity in the conditions to dynamically enable/disable the schedule.  Like the cases discussed.

By not combining this you can get confusing behavior: a schedule with the tag “Holliday” that has a condition that is based on an helper entity “OddWeek”. 

So it would work but the management of the tags and conditions would be more cumbersome.

**Comment by bikeymouse** [comment]
To keep this issue open: this is to show that I'm still hoping that something like a vacation mode will be realized!

**Comment by pdwonline** [comment]
> Anyone who has any ideas that would help overcome this issue, or another strategy for the filtering, please share.

If the scheduler integration has the ability to acommodate groupsnames, it would be possible to filter schedules based on a certain groupname. See suggestion for [Scheduler integration](https://github.com/nielsfaber/scheduler-component/issues/112)

**Comment by nielsfaber** [comment]
Support for tags will be added in the next release.
See [documentation](https://github.com/nielsfaber/scheduler-card#tags) for more details on how it works.

You can assign tags to schedules here:
![image](https://user-images.githubusercontent.com/16861605/130319846-1e7ed591-d8b9-476a-a808-cabcf5a0fc8a.png)

You can also choose to display the tags in the overview using `display_options`:
![image](https://user-images.githubusercontent.com/16861605/130319831-2a587157-5419-4e2e-88f1-b10fc64195bd.png)
