### ISSUE TITLE
Target selector

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#359]
With blueprints came the target selector. It would be good if the scheduler-card could embed this, so we could select areas, instead of manually selecting all of the entities in that area.

**Comment by Misiu** [comment]
That's an awesome idea. To be sure, you suggest replacing the `ENTITY` selector with target selector (similar to what we get in blueprints or in automation editor)?

![image](https://user-images.githubusercontent.com/1741838/114860343-2a276680-9dec-11eb-8a84-bc2b56dbea0f.png)

**Comment by nielsfaber** [comment]
What would be a use-case for creating a schedule for an area, rather than an entity / device (I don't know what's the difference between them inHA these days) ?
I prefer to keep the GUI simple as it is now.
The target selector of HA is not particularly simple if you ask me.

**Comment by Misiu** [comment]
@nielsfaber for example: turn off all lights in the bedroom at 10 PM. So when you add a new device (or entity, not sure the difference too) the scheduler will include them without any changes.
The functionality will stay the same because you can select entities if you want, but you will be able to select devices and areas.

**Comment by nielsfaber** [comment]
That makes sense actually.
Perhaps scheduler could treat them similar to a group, so it calculates the actions of the entities contained by the area and offers them as options.

IMO replacing the current entity picker in the scheduler by the HA target selector is a separate discussion (its more a GUI thing rather than adding functionality to the card).
I guess for larger HA setups the scheduler card may become a mess, on the other hand if you use proper filtering for the card it works OK.
Maybe I will create a poll for this, since I like to collect user feedback for making such decision.
Dropdowns have pro's and con's if you ask me (especially on mobile devices).

**Comment by KTibow** [comment]
> Perhaps scheduler could treat them similar to a group, so it calculates the actions of the entities contained by the area and offers them as options.

Options for what?

**Comment by derekoharrow** [comment]
> That makes sense actually. Perhaps scheduler could treat them similar to a group, so it calculates the actions of the entities contained by the area and offers them as options.
> 
> IMO replacing the current entity picker in the scheduler by the HA target selector is a separate discussion (its more a GUI thing rather than adding functionality to the card). I guess for larger HA setups the scheduler card may become a mess, on the other hand if you use proper filtering for the card it works OK. Maybe I will create a poll for this, since I like to collect user feedback for making such decision. Dropdowns have pro's and con's if you ask me (especially on mobile devices).

I don't think the way to do this is to present a list of devices in the area when creating the schedule.

The idea of using areas would be that you can select the area but that the devices within that are can change over time.

I could add a new light to my bedroom area, but I don't want to have to go back into the schedule to change it and select the new device. It should lookup devices in the area at run-time.
