### ISSUE TITLE
Time based condition on integration other than sun (i.e. jewish calendar)

### ISSUE THREAD

**Issue by kaaspad** [nielsfaber/scheduler-card#367]
First of all I'd like to say that this is really the missing holy grail of home assistant, to say that your work is amazing would be a gross understatement!! Thank you so much - it is beyond me how this is not including as default in HA - it should be there before even automations!!!
So to my issue/feature request. Today you have an awesome little button that is sunrise/sunset option which allows you to make the time based on sunrise sunset (with offset).
There is an integration called Jewish Calendar - which gives very important times for Jewish people, the times are sensors that are created in HA. How difficult would it be to add an option similar to the sunrise/sunset button of another button that will allow to choose from the time lists in jewish calendar?
Thanks

**Comment by menocode** [comment]
@kaaspad agree that this is a superb add on. Really helpful for me. 
I would also like to see an option to pull variables from the Jewish Calendar and set schedules based on the those times. Kudos on the work

**Comment by KTibow** [comment]
One of the goals of this integration is to not get too complex.

**Comment by menocode** [comment]
It could be an option to be turned on in YAML.

**Comment by kaaspad** [comment]
@KTibow I totally understand, but actually I thought this would make things easier for a lot of people who use both integrations. Could be a YAML setting to enable the button like menocode said and once its enabled you'd be choosing a few different times similar to sunrise and sunset

**Comment by nielsfaber** [comment]
To understand this request a bit better, I read this page: https://www.chabad.org/library/article_cdo/aid/134527/jewish/Zmanim-Briefly-Defined-and-Explained.htm, it seems to describe the subject quite well.
My understanding is that the Jewish religion defines certain moments of the day for (mostly) prayers, these times are related to sunrise/sunset or angle of the sun.
In that sense, [Jewish Calendar](https://www.home-assistant.io/integrations/jewish_calendar/) seems a bad name for it (it suggests that its related to the date rather than time).
There seem to be quite some analogies with the [Islamic Prayer Times](https://www.home-assistant.io/integrations/islamic_prayer_times/) component.

I have the following improvements on my planning, which seem to be related to this request:
- Add hebrew translation (in progress)
- Add support for RTL (right-to-left) text display
- Allow more than 2 hours offset from sunrise/sunset

Implementing all of these will take quite some time, and I consider this a priority.

I think integrating this with scheduler has quite some impact, as both in the scheduler-component and the scheduler-card quite some essential parts need to be touched.
As @KTibow says, the goal is to keep the scheduler integration as simple as possible.
Simply since all code needs to be maintained, and currently this is mostly done by myself.

In the past I have rejected requests for allowing users to use dawn/dusk and sun elevation/angle for schedules, since I consider them too specific.
On the Jewish Calendar page you can also see that only 0.2% HA installations use this component, and only a VERY small portion of those will also use this scheduler component.
Therefor I am leaning towards the same judgement for this request.
I also wonder if the same functionality can be achieved by using sunrise with offset.
@kaaspad could you give feedback on this?

**Comment by kaaspad** [comment]
@nielsfaber first of all you are right, it should be called "Jewish Calendar" it should be called "Zmanim" which literally means times in Hebrew, but all know that it refers to these exact times. The "Zmanim" are similar to the islamic prayer times, just there are a lot more - In Islam it would be just 5 times a day every day of the year, while with Zmanim its more complex but that complexity is actually well taken care of by the Jewish Calendar integration.
Regarding the Hebrew translation - I'm happy to finish that today - just point me to the direction of what needs to be done and I'll complete that. Regarding RTL - not sure where you want to use RTL - but its quite simple with CSS or Markdown as they have a built in tag. I haven't seen a GUI element that needs this (which is not already taken care of by HA's main system).
Some of the functionality can be achieved with the sunrise and sunset offset - but some is more complex and does take elevation/angle in to consideration - This is why to just make it whole dependent on the other integration would make sense.
I'd be happy to take a shot at it - my Python is rusty at best, but if I could understand what you did with sun.sun, I could probably replicate.
One other totally unrelated question feature request - how difficult would it be to have an option on a created schedule to "Export to automation", are you just creating these automations when you create a schedule?
Thanks for your response

**Comment by menocode** [comment]
Here is my two cents on the use case. Perhaps there are different ways to solve for. 

Use case 1
Use schedule to turn on lights and HVAC on shabbat and holidays as religious jews do not turn on electric appliance on these days.
Sabbath always falls out on Saturday, Holidays can fall any day. The start and finish times are similar in they are on offset before and after sunset. I want to be able to use the same schedule for shabbat and for holidays. Shabbat is easy- set every Saturday. holidays move around. 
Potential solution. In the jewish calendar there is an entity called 
binary_sensor.jewish_calendar_issur_melacha_in_effect
Essentially that turns on when Sabbath or a holiday starts and off when it ends.
So if the there is an offset to that event, I set the schedule to work every time that event is on and off when the event goes off.
 perhaps setting the condition to that event works today. 

Use case 2 
I want a modular set of schedules that allow me to toggle on/off a set of sub schedules.
For example 
Top level schedule 
"Sabbath mode" 
Sub schedule 
Living areas
Hvac upstairs 
Hvac downstairs
Lights bedroom 1

**Comment by nielsfaber** [comment]
@kaaspad 
> Regarding the Hebrew translation - I'm happy to finish that today - just point me to the direction of what needs to be done and I'll complete that. 

This is in progress, someone already provided a translation. In the next update of the card it should become available for everyone.

> Regarding RTL - not sure where you want to use RTL - but its quite simple with CSS or Markdown as they have a built in tag. I haven't seen a GUI element that needs this (which is not already taken care of by HA's main system).

I think you're underestimating this. Try setting your HA account language to Hebrew and see how messed up the card becomes.
There are quite some custom GUI elements in the card.

> Some of the functionality can be achieved with the sunrise and sunset offset - but some is more complex and does take elevation/angle in to consideration - This is why to just make it whole dependent on the other integration would make sense.
I'd be happy to take a shot at it - my Python is rusty at best, but if I could understand what you did with sun.sun, I could probably replicate.

Ofcourse you're free to give this a try yourself, but I hope you will also keep maintaining it if so.
For a starting point, check out all references to 'sun' in these files:
- https://github.com/nielsfaber/scheduler-component/blob/main/custom_components/scheduler/timer.py
- https://github.com/nielsfaber/scheduler-component/blob/main/custom_components/scheduler/const.py

I think the part for the card is more difficult, I'm working on implementing sunset/sunrise for the time schemes. It is hard to make a simple GUI with all these options.

> One other totally unrelated question feature request - how difficult would it be to have an option on a created schedule to "Export to automation", are you just creating these automations when you create a schedule?

Scheduler does not use (parts of) automations under the hood, so the exporting would require a translation part. 
Also HA does not offer services to create automations on-the-fly, it is not that easy to create one.
What would be the use-case for this?

@menocode 

> I want a modular set of schedules that allow me to toggle on/off a set of sub schedules.

There is another thread to discuss the option of assigning 'tags' to schedules.
If this is in place, it would become possible to toggle sets of schedules.

As for use-case 1, you could check out if this could be done with the workday integration.
This allows users to define weekend+holiday schedules, perhaps Sabbath could be included here.

**Comment by IsaacBreuer** [comment]
hi all . I am currently using the schedules alongside the Jewish calendar. this is extremely useful for observant jews who cannot turn any electronics on or off during shabath or yomtov (Jewish holidays) and everything has to be automated from before. here is my setup. 
I have created a select option that gets filled in with holiday from Jewish calendar integration, than i use this select as conditions on the scheduler card, having seprate schedule for each yomtov ( that's why I opened issue #353 as I have so many different schedules)
