### ISSUE TITLE
Separation between admin level and user level functionality.

### ISSUE THREAD

**Issue by Canonfodda** [nielsfaber/scheduler-card#428]
This integration and its supporting card, in my opinion, overcome a huge amount of tedious configuration and card manipulation (see Keymaster) that is sort after in the HA automation. There are 2x things that I would like to discuss. 

**1.** Sensors and Binary_sensors missing from the options area. Yes, this could be solved with scripts and setting supporting booleans for this purpose eg: testing of temperature sensors in ZWave & Zigbee devices. But adds a layer of obscurity to the functionality. 
**2.** the separation of Admin configuration/setup/card positioning and views. and User usage and timer configuration. This is a bigger discussion as I have this issue with most automation systems. Some cards do this with card locks, others don't do this at all. Having the scheduler times be varied or locked out by a PIN would be a great consideration. This could be achieved by a set of user codes like the views can be exposed or not depending on users. I am wanting to use HA in environments like AirBNB environments where there needs to be a separation between admin and user but most of the functionality still needs to be available to the user for changing of their environment and timing in their environments.

Just a consideration as I will also be discussing this with the general HA team as its an area IMHO is not being architeched within the greater HA software design environment and it will eventually put a huge barrier between the larger integration and use of HA in residential usage. 
I would also appreciate any discussion from you the author of this integration as to potential other work arounds that would be available to allow the user and not the admin to change timings only of the scheduler. 

With thanks for the awesome integration and the work for adding to the functionality of the HA environment.

**Comment by lmagyar** [comment]
This is partially a duplicate of #282.

**Comment by lmagyar** [comment]
You can use [custom:restriction-card](https://github.com/iantrich/restriction-card) to lock out users eg. with a PIN.

**Comment by Canonfodda** [comment]
Agreed, _**This is partially a duplicate of #282.**_ and I have been watching this case #.
_**You can use custom:restriction-card to lock out users eg. with a PIN.**_ And I will give this a try. Looks like I can lock out admin level users, but understandably it would elevate non-admin users to allow to change time schedules.
Many thanks and may be this can be closed as a duplicate of #282 and I will follow it there. 

Many thanks for this scheduler.

**Comment by nielsfaber** [comment]
For next time, please keep your requests short and to the point and use the predefined issue templates.

> 1. Sensors and Binary_sensors missing from the options area. Yes, this could be solved with scripts and setting supporting booleans for this purpose eg: testing of temperature sensors in ZWave & Zigbee devices. But adds a layer of obscurity to the functionality.

What do you mean exactly? What is an option area?
I don't see the relation with user permissions. 
There is support for assigning conditions based on sensor states, but I'm not sure if this what you're asking for.

As for the rest of your request, I agree with @lmagyar and I have #282 high on my priority list.
Support will soon be added (restored) to allow non-admin users to use (view+modify+add+delete etc) scheduler-card.
You may choose to use the Restriction Card or set the `require_admin` flag for certain lovelace views in case you want to limit permissions between users.

Other than that I have no intention of adding user-specific functionality to the scheduler-card (the code is already too big to manage).
As you already said, your request seems mostly related to HA architecture rather than this card specifically.
