### ISSUE TITLE
Trying to change the climate entity in a schedule throws an error

### ISSUE THREAD

**Issue by redlegoman** [nielsfaber/scheduler-card#435]
### Expected behavior
When I click on an existing schedule to change the entity from one climate entity to another, it should allow me to save without an error

### Actual behavior
I get an error:
Something went wrong!
Message format incorrect: length of value must be at least 1 for dictionary value @ data['timeslots']

Response error: 400

Please report the bug.

### Steps to Reproduce
Click on existing schedule, already setup, but with the "wrong" climate entity
Click on "ACTION" and choose different entity:
![image](https://user-images.githubusercontent.com/1895294/130863573-1b94c006-e732-42eb-a0f0-d5ea9f816400.png)
Change the entity:
![image](https://user-images.githubusercontent.com/1895294/130863607-dbdb47d1-370b-46eb-b7ec-df3a23a48714.png)
Click "Next"
![image](https://user-images.githubusercontent.com/1895294/130863635-4038892d-2793-489d-9c8d-13fefce2b972.png)

Click "SAVE"
See error:
![image](https://user-images.githubusercontent.com/1895294/130863658-28abb6b4-5fec-4976-8868-cf69ab2dde82.png)

**Comment by nielsfaber** [comment]
The reason you're seeing this error is because you're trying to save an empty time scheme (it has no timeslots with actions, so no purpose).
I should probably make this more clear by making the 'save' button greyed out, to prevent the user from saving the time scheme as such.

There is currently no functionality in place to preserve actions assigned to timeslots when switching entities, so they will be wiped out.
Preserving the actions is rather hard to do because entities may have different supported action configurations.
Differences could be very subtle such as different min/max temperature range for climate entities, support for dimming of a lamp instead of on/off switching etc., so the overlap between 2 entities is not easy to compute.

**Comment by nielsfaber** [comment]
I made some changes to have the save button greyed out if all timeslots are empty, and also try to keep the assigned actions if they are also available for the newly assigned entity/entities. I'm not sure if this is covering 100% of cases, but it should help.
