### ISSUE TITLE
Schedule list on card should use the "Name" as title

### ISSUE THREAD

**Issue by sarahmva** [nielsfaber/scheduler-card#455]
### Proposal
[clear description of what you want to see changed or added]
I would like to see the Name added to the list of schedules. If no name is entered, the current behavior is fine. 

### Additional info
[some example of how the new functionality should look like]

Current behavior:
**4x switches: Turn on**
In 5 hours

New Behavior
**Outdoor Lights** _{derived from Name field in Options}_
4x switches: Turn on
In 5 hours

**Comment by nielsfaber** [comment]
This is not really a feature request since it is already possible by card configuration (see https://github.com/nielsfaber/scheduler-card#display-options).
Note that this customisation is only accessible by yaml (not card editor).

if you want to suggest changing the _default_ display mode, please elaborate (also consider that assigning name to a schedule is optional).

**Comment by Stooovie** [comment]
Excuse me, what is the actual point of having the Name under Options? I thought this was to set the name in the actual lovelace card, but so far I'm not sure what it actually does.

**Comment by nielsfaber** [comment]
@sarahmva Your improvement is added in version v2.3.0 of the card.
Please test it out and close the issue if you are satisfied with the result (otherwise please let me know).
