### ISSUE TITLE
"Over cool by _ degrees" or "Over heat by _ degrees"

### ISSUE THREAD

**Issue by liquidbear99** [nielsfaber/scheduler-card#474]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
I'm looking for a easy way to set my thermostat to overcool or over heat by a certain amount of degrees.

### Additional info
This could be configured in the "options" area on an individual time/temp setting.

**Comment by nielsfaber** [comment]
Scheduler only supports actions that can be executed by means of services.
Since the [climate.set_temperature](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature) service only supports setting temperature **to** X degrees (rather than **by** X degrees), I cannot fulfil your request.

You could create a script which checks the current setpoint and adds some step value, and configure scheduler to execute this script instead (its also possible to pass the step value from scheduler). 
Otherwise I don't have any idea how to accomplish your goal.

**Comment by liquidbear99** [comment]
Thank you so much for this response. Would it be possible to implement it in this integration by sending a set temp that is above the original set temp, then lowering that temp to the original goal one when it reaches the higher one. Ex. at 68 deg set the temp to 71 then once it hits 71 reduce the set point to 70 deg.

**Comment by nielsfaber** [comment]
Scheduler only supports actions that can be executed by means of services.
