### ISSUE TITLE
Tuya aka TS0601 Heat mode =valve is permanently kept fully open

### ISSUE THREAD

**Issue by boxi360** [nielsfaber/scheduler-card#478]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
On Tuya aka TS0601 I am using those on Auto and only setting the temperature. When I switch to Heat and specify let’s say 18 degrees, the valve stays open 100%, because well…it is in heat mode.

So to make it work I would either have to add custom Set temperature, like I had before, or make schedules so I do Heat and set value and then after 5 minutes switch to Auto. Though it will be killing my battery because the valve will have to fully open :frowning:

Modes:
Off=valve is permanently kept fully closed
Heat=valve is permanently kept fully open
Auto=valve is regulated according to preset mode

Preset modes (sorry if some incorrect information provided, this is my best knowledge):
Auto - temperature is maintained according to programmed schedule (points in time, hours, workdays/weekends)
Boost - valve is kept fully open for time defined as boost_time (in secs), then returns to auto mode
Comfort - valve constantly maintains temperatured defined as ‘comfort’
Eco - valve constantly maintains temperatured defined as ‘eco’
Holiday - valve maintains temperature defined as away_preset_temp for away_preset_days, then returns to auto mode (usefuly when you leave home, yuo want to keep low temperature whilr you are away and you want to return temperature to normal before you return)
Manual - valve maintains fixed temperature set manually on the valve as current_heating_temp
Complex - temperature is maintained according to programmed schedule but one changed the current heating temp so temporarily temp set manually is maintained. Valve will return to schedule on next scheduled time point (think of is as temporary deviation from programmed schedule).

do you have a way to implement it somehow in your addon ?

### Additional info
[some example of how the new functionality should look like]

**Comment by Banzarykey** [comment]
I have the same issue, the set temperature option is missing as well so i used the custom one however that now wont show either.  
Having a built in solution for this would be fantastic.

**Comment by nielsfaber** [comment]
I agree it would be nice if scheduler can work well with this device.
Ideally an action should be created to set `hvac_mode` to `auto` together with a temperature setpoint.
Meanwhile you would have to keep the `preset_mode` to `manual` at all times, otherwise the device might not respond.

Did you try to add the extra action via `customize`?

**Comment by nielsfaber** [comment]
I made a small test for this.
Since I don't own the `TS0601`, I used the [MQTT climate integration ](https://www.home-assistant.io/integrations/climate.mqtt/)to make a similar climate entity:
![image](https://user-images.githubusercontent.com/16861605/142731447-eff791ee-ed8e-46c0-bd4d-95ff37625055.png)

Next I customized scheduler-card to hide built-in actions and add a new 'heat' action which sets hvac_mode to auto:

```yaml
customize:
  climate.tuya_mock:
    exclude_actions: # names of actions to hide
      - heat
      - set mode
      - set preset
    actions: # configurations for actions to add
      - service: set_temperature
        service_data:
          hvac_mode: auto
        variables:
          temperature:
            min: 10
            max: 25
            step: 0.5
            unit: '°C'
        icon: 'hass:fire'
        name: "heat[ to {temperature}]"
```

As a result I can only choose 'heat' or 'turn off' actions in the card (I recommend to stay away from using the presets, keep it at manual always):
![image](https://user-images.githubusercontent.com/16861605/142731566-8779815a-fc26-4941-a615-9a5b4f9ba3dc.png)

Now in the timeslots from 08:00 - 16:00, 16:00 - 00:00, the device is set to `hvac_mode` 'auto', together with the configured setpoint temperature.

You can check the action of the scheduler in the logbook (the screenshot of the entity configuration above also confirms this):
![image](https://user-images.githubusercontent.com/16861605/142731675-05320cfb-c671-4648-8deb-c6a027b67652.png)

(note that the schedule did not trigger at exactly 16:00, I triggered it manually a little bit after since I was too slow)

My conclusion is that no changes are needed for scheduler to make it work.

Please realize that this device does not comply with the [HA mode definitions](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes), it is not OK that the device goes to 100% heat in `hvac_mode` 'heat' (also `hvac_mode` 'auto' is intended for other uses).
I think it is sufficient if the support for the TS0601 can be achieved with customization as shown in this message.

**Comment by MattWestb** [comment]
In ZHA we is some user and devs that is having problem getting one good working native schedules for out TRVs.
The problem we can read and writing the attribute to and from the device and getting it save in the device and in the ZHA attribute data base.
But tuya is using time slots and locked day patterns that can being changed.

If implanting one "tuya TRV mode" it can being used for ZHA. Z2M and deCONZ integration and getting node time programs in our devices.

What i taking about is the time series in the device that is having there own for mate.
My device dont have it so i must doing all in software sending new temperature "online" but for device with time programs in its wold being great having this card for doing it nice and easy.

Shall i making one separate future request of is this OK ?

Best regards.

**Comment by nielsfaber** [comment]
@MattWestb This integration is not suitable for creating schedules to save on the TRV itself. You don't have to makle a request for it.

@boxi360 Any updates on this? Did you get it working with the customization I shared before?

**Comment by boxi360** [comment]
@nielsfaber 

> @MattWestb This integration is not suitable for creating schedules to save on the TRV itself. You don't have to makle a request for it.
> 
> @boxi360 Any updates on this? Did you get it working with the customization I shared before?

Hi Niels,
sorry for late reply... I have adjusted the entities (use only the "manual" mode and hvac_modes: I have removed heat so your script works.

![image](https://user-images.githubusercontent.com/60380162/144874047-e503f297-a980-479a-a5a9-c3f70bf632e2.png)


Your suggestion I have not been able to implement at least have not managed.

**Comment by nielsfaber** [comment]
I am closing this issue since the problem seems to be resolved.
I [added a section](https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions) in the documentation to help others with the same problem.
