### ISSUE TITLE
actionable notifications

### ISSUE THREAD

**Issue by leonardpitzu** [nielsfaber/scheduler-card#490]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The card should offer a way to insert the necessary text for having push notifications, like:

`service: notify.notify
data:
  title: House Cleaning
  message: Do you want to clean the house?
  data:
    push:
      category: vacuum`

This sends out a notification which upon "long push" offers a menu (in my case 2 items - it asks the user to select vacuuming or mopping).

### Additional info

Next to the `Title` or `Message` a checkbox like `Send Actionable Notification` would be great. Once checked another text field should come up so that the user can enter the `category`.

**Comment by leonardpitzu** [comment]
Do you think it makes sense or should the FR be closed?

**Comment by nielsfaber** [comment]
Your request is ignored because it is way too specific.
The `data` attribute for the notify [service ](https://www.home-assistant.io/integrations/notify/#service) is not generic, i.e. it depends on the targeted device/platform what formatting is supported/required. As far was I know, notifications are only supported for iOS / Android devices through the mobile app, but there are [many more platforms](https://www.home-assistant.io/integrations/#notifications). The card cannot tell whether the notification is sent to an iOS / Android device or different. 

For iOS / Android you can add actions by providing them in the service, see [here](https://companion.home-assistant.io/docs/notifications/actionable-notifications/#building-actionable-notifications). There is no possibility in the card to add fields to have users dynamically add buttons with actions + titles.
Providing `category` is [deprecated](https://companion.home-assistant.io/docs/notifications/actionable-notifications/#migrating-from-categories).

I suggest you to look at [customize](https://github.com/nielsfaber/scheduler-card#customize), you could use it to add extra actions to the card. It would be possible to create a actionable notification this way, but the actions have to be fixed / hard-coded.
