### ISSUE TITLE
Feature Request: pause between earch item

### ISSUE THREAD

**Issue by skelgaard** [nielsfaber/scheduler-card#494]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

if i add 5 or more items to turn on/off at same time, it is not always it get all items switched.
i have the same problem if i do a normal automation with more items in them.
if i add a 1 sec pause between each item, they work just fine, so being able to add a pause between each would be a great additional that could be optional setup on an item

### Additional info

could just be an input box where you could set a number or a slider

**Comment by nielsfaber** [comment]
> if i add 5 or more items to turn on/off at same time, it is not always it get all items switched.
i have the same problem if i do a normal automation with more items in them.

I think you should focus on the cause of this.
I can switch all my smart lamps (about 15) in the house simultaneously without a single one failing.
Perhaps there is an issue with the integration you are using?

I am not planning to add any feature for delaying execution between multiple tasks.
It feels like an over complication of the card, and, as you say already, the problem is not due to scheduler. I believe other users don’t have this issue so won’t benefit from this feature.

If you want to achieve this, I suggest you create the sequence in a script and trigger this one from scheduler instead of the devices.

**Comment by skelgaard** [comment]
The purpose for me of using your card is to not having to use scripts to create stuff like this and some of the purpose of this card goes a little away if i have to sit and create scripts for the wife to be able to add automations instead of she can click in the interface and add them her selves.
Yes the shedular and scheme are still better than normal automation, but she can't add or remove stuff as easy then.
try having 5 tuya or shelly based sockets (wifi once) and turn them off at once... i often have one that doesn't switch on/off.

**Comment by haseat** [comment]
@skelgaard What items are you talking about? Zigbee lights? If yes, that sounds to me like a problem with the zigbee mesh. I've had similar problems when sending multiple turn on/off commands to my lights in the livingroom using lightgroups in HA. By doing so, a turn on/off command was sent to each individual light, and some of those commands got lost almost every time. My problems disappeared once I moved over to lightgroups in deconz. This results in sending one turn on/off command to the whole group and always works.

**Comment by skelgaard** [comment]
@haseat i don't have the problem with pure zigbee light items.... but i also have wifi sockets connected and other items that do not run zigbee... with them i have the problem that they don't always all get changed at once
