### ISSUE TITLE
Scene selector in the make scheme view

### ISSUE THREAD

**Issue by Mother-Goose** [nielsfaber/scheduler-card#501]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Allow the user to select which scenes are activated throughout the day in the ‘make scheme’ view. 

At the minute I believe the only way to activate scenes is to have one schedule for each scene and trigger each one individually through the day.
 My use case is setting heating (trvs) on/off at points during the day in different rooms. I have scenes set up for morning, work hours etc and would like one view where I can select for instance to set the morning scene at 7:00 and the work scene at 9:00 etc. 

### Additional info

It should look like the make scheme view. In the action section there should be an option to activate one /many of the scenes for each time slot. 

Would be very powerful way to view what is happening through the day.

**Comment by nielsfaber** [comment]
This is not possible since each scene is a different entity in HA. 
It is not possible to define different entity per timeslot in the scheduler-card. 
I don't see this possible to change due to the fact that the selection of entities is done in a separate page.

Maybe you could create an input_select with all  different scenes as options, and trigger this using scheduler?
Ofcourse you would also need to create an automation to trigger the actual scene when the input_select changes.
