### ISSUE TITLE
Add arrows to select time fields

### ISSUE THREAD

**Issue by Gio-dot** [nielsfaber/scheduler-card#515]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

On smartphones is quite impossible to select short time fields, so it is not easy to check what action is in that fields. I suggest to add two navigation arrows to select time fields. 

### Additional info

Left and right arrows are used to navigate time fields. It may help to check or adjust settings on smartphones:

![Screenshot_20220125-083559_Home Assistant](https://user-images.githubusercontent.com/55327160/150934233-089ba730-d1c2-4df1-ae0c-b44241d8a42c.jpg)

**Comment by nielsfaber** [comment]
I agree that on the smartphone small timeslots are not easy to manage.
However, I think your proposal only is a partial solution, since it would only help adjusting the action, it is still very hard to accurately change the time.
I am thinking about adding a 'zoom' effect when a small timeslot is selected.
It could work well combined with the arrows as you are proposing (however I don't think they belong in the spot where you drawed them).

This feature will take some time to implement, so I am asking for some patience.
