### ISSUE TITLE
Add the option (button) to "run now" a schedule

### ISSUE THREAD

**Issue by srodighiero** [nielsfaber/scheduler-card#540]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

This could be sort of a button, side placed after a schedule on the main view, giving the possbility to run the actions immediately instead of waiting the scheduled time.

This could help also to test a schedule, as well as to run a schedule immediately in case of need.

### Additional info

![image](https://user-images.githubusercontent.com/4833164/157854391-7c037656-4b5e-477c-81ea-502dd8fa84db.png)

**Comment by nielsfaber** [comment]
There have been similar requests before, but I don't see this a good solution because it doesn't really fit in the available space of the card.

The card size is adapted to the screen size, so I have to take into account that the card will be narrower for some users, example:
<img src="https://user-images.githubusercontent.com/16861605/157928237-4b642257-66ba-47b2-bad9-0d21daf7a196.png" width="75%" height="75%">

Adding a button here would cause the text to break across multiple lines, which makes things worse for most users.
I don't feel much for making such UI aspects user configurable (optional) either, as it would involve extra effort for me to design and maintain.

I think it is better to use a [button card](https://www.home-assistant.io/lovelace/button/) for specific schedules you want to be able to trigger manually.
