### ISSUE TITLE
Set temperature in "Auto Mode" not possible

### ISSUE THREAD

**Issue by MikeOfGit** [nielsfaber/scheduler-card#541]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The Homematic IP app allows to set temperature in Auto Mode to a desired level. In scheduler this option is not exposed (see screenshot).
![image](https://user-images.githubusercontent.com/76949179/158056264-483cc0f1-0e3b-49d7-857f-e43c0bea3f8f.png)

One must use Heating Mode to set a desired temperature which results in constant heating even if environment temp is already high enough. I'm not sure if this option is exposed via API but it would make settings more easy for me.

### Additional info

Maybe it's possible to make that temp slider available in automatic mode like here in Heating Mode:
![image](https://user-images.githubusercontent.com/76949179/158056420-f7641569-6af4-48f5-82db-59f36f3007e4.png)

I'm unsure if the Rest API docs on https://homematicip-rest-api.readthedocs.io/en/latest/gettingstarted.html expose anything useful. At least I wasn't able to find anything suitable.

**Comment by nielsfaber** [comment]
When setting a climate entity to hvac mode auto, there shouldn't be a temperature applied.
See [here](https://developers.home-assistant.io/docs/core/entity/climate/) for the definition in HA:
> HVAC_MODE_AUTO: The device is set to a schedule, learned behavior, AI.

In contrast to:
> HVAC_MODE_HEAT: The device is set to heat to a target temperature.

I follow the definitions from HA, so I'd say that your problem is caused by the homematic integration.

If you want to do so anyway, see [here](https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions) for instructions for a workaround.
