### ISSUE TITLE
Scheduler per calendar week, per month (e.g. first Monday, last Saturday, "on the 5th"), per quarter, per year, per ???

### ISSUE THREAD

**Issue by chscherrer** [nielsfaber/scheduler-card#545]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

loving this scheduler-card, yet missing a couple more options to configure my automation and devices like
- Turn on winter decoration only from first Sunday in December until 6 of January
- Turn on summer evening decoration "bottle lights" only weekends from beginning of May until end of August
- Turn on my thermostats only during heating season from 1st of September to 31st of Mai
- Run my script reminding me every first Monday of every even-numbered month to bring carton for recycling out
- Run my script assembling my net power consumption every end of quarter
- ...and so many more fun things to do seasonally

### Additional info

I very much like the way the scheduler-card is presenting how schedules are set - new interval possibilites should show analogous.

**Comment by nielsfaber** [comment]
Scheduler already allows to set a date period during which the schedule is active:
<img src="https://user-images.githubusercontent.com/16861605/160060040-24d35854-9068-45c1-ac96-c471cc023bc4.png" width="75%" height="75%">

So I'd say that these items are already supported:
> Turn on winter decoration only from first Sunday in December until 6 of January
Turn on summer evening decoration "bottle lights" only weekends from beginning of May until end of August
Turn on my thermostats only during heating season from 1st of September to 31st of Mai

The only side-note is that the period setting includes the year, so it will not automatically repeat the following years. However I think it is a relatively small effort to update this once per year (you could even schedule a push notification as a reminder 🙂 )

These cases are much harder to support:
> Run my script reminding me every first Monday of every even-numbered month to bring carton for recycling out
Run my script assembling my net power consumption every end of quarter

I wouldn't know how to implement this without making the card very complex.
Even through HA automations I think this is not easy to achieve.
The only way I could think of, is to to have the date-picker used for setting the date period allow for defining multiple occurences (instead of a range). In this case you would have to manually mark the 1st Mondays per 2 months etc. 
However, the scheduler card uses the date picker element from HA and it doesn't seem to support such functionality.

as a workaround, did you consider to create some template binary_sensor representing the date pattern and assign these as conditions to the schedules? 
If you create a schedule which runs every Monday, combined with a binary_sensor which indicates whether its the first week (or first monday)  of an even month, you would be able to create the behaviour you are looking for.

**Comment by linux-guru-com** [comment]
> [...]
The only side-note is that the period setting includes the year, so it will not automatically repeat the following years. However I think it is a relatively small effort to update this once per year (you could even schedule a push notification as a reminder 🙂 )
[...]

The solution you mentioned is generally ok, but IMHO not very "elegant".
Would it be possible to add certain wildcards for each date element, maybe such as used in the Linux Cron expressions?

**Comment by lynntryanderror** [comment]
Hi,

first of all. Your scheduler card is amazing. Soo easy to use, really good and userfriendly design. And i use it only ~2weeks.

I'm looking also for a solution to get for example notifications for:

Every 2. friday (every 2 weeks) to remember me to take the trash bin out.
Every month to clean the gutter and the water filtration system.
Once a year to clean the UV light from the water system.

For example in Outlook you can choose between, Daily, Weekly, Montly,... when you schedule a meeting. i think more poeple can use this a well.

Thanks a lot
Lynn
