### ISSUE TITLE
Allow tag exclusion

### ISSUE THREAD

**Issue by pterisaur** [nielsfaber/scheduler-card#563]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

It would be amazing if we could customize the card to include AND exclude specific tags. 

Example use cases:
- Show only holiday weekday items: include "holiday" and exclude "weekends"
- Show only kids' weekend items: include "kids" and exclude "weekdays"
- Show only non-kid weekday items: exclude "kids" and "weekends"

### Additional info

This would be a simple addition to the YAML; include a "not_tags" or "exclude_tags" line item.

**Comment by nielsfaber** [comment]
This feature is added to release v2.3.5, you can use `exclude_tags` (YAML-only for now) to exclude items.
The documentation has been updated to describe the functionality.
Could you please update to this version and test it out?
You can close the issue if the request is fulfilled, otherwise let me know.
