### ISSUE TITLE
Crashing Browser / App

### ISSUE THREAD

**Issue by peterguy04** [nielsfaber/scheduler-card#566]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.4

### Component Version

3.2.10

### Bug description

Makes browser tab unresponsive, forcing me to close and reopen. This happens in both Chrome and the HA android app

i believe its similar to https://github.com/nielsfaber/scheduler-card/issues/264

### Steps to reproduce

create scheme , save it and reopen , it doesn't seem to happen instantly but nearly always crashes.

### Additional info

![image](https://user-images.githubusercontent.com/45408070/172475782-b34b67fb-9769-4aa8-beef-f42c779a5c69.png)

Home Assistant Core 2022.6.3 (Docker)

**Comment by nielsfaber** [comment]
This issue was discovered by user @nobodyguy as well, who also made a fix for it: https://github.com/nielsfaber/scheduler-card/pull/557
I will make a new release soon which should contain this fix. I will keep you posted.

**Comment by nielsfaber** [comment]
@peterguy04 This problem should be solved by updating to the v2.3.5 release.
Could you please update to this version and test it out?
You can close the issue if all works OK now, otherwise let me know.

@TTLucian If you experience an other issue, please open a bug report for it. This doesn't seem related. Ofcourse it is wise to update the card as well, maybe the problem is fixed in the meantime unintended.

**Comment by peterguy04** [comment]
Thanks very much, all seems good now
