### ISSUE TITLE
Timer card / Timer as default behavior 

### ISSUE THREAD

**Issue by Chaos02** [nielsfaber/scheduler-card#567]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

> The Request of a Timer mode for HA has been issued before, even on this repo. However as there still is no Timer/scheduler cards natively from HA I've elected to "reopen" the timer request.

In many cases you want to just setup an event for something in like an hour or so and forget about it.
With this card it is easily doable by configuring the time to be in X minutes, however it is tedious and clumsy.

### Feature Request: 
My request is that there will be a second repo, maybe a fork, that uses the same scheduler backend and shares much code with this one, that will enable users to have a timer card.

### Additional info

The Timer card in question, should act in the following ways:

- Similar to the scheduler card, the timer should display already created "permanent" timers to just enable and start the timer.
- When an already configured timer is activated, the card shall schedule the configured actions to be executed in now + x minutes.
- (optional): Let the time remaining display be handled by the client via Javascript instead of sending the time to the client dashboard from HA.
- When creating a new timer the following behaviour would be ideal:
  - Default time offset (example: `+20m`) can be configured in a config file
  - A checkbox/switch to enable a second action with a second time configurator (example: `+40m`). This second action should either be executed in `now + X mins` or in `now + X + Y mins`, where `Y` would be the second time configurator. (Whatever would be better for usability)
  - The default behavior should be to delete the timer after execution, but it shall be configurable for the aforementioned permanent timer collection.

_Maybe_ there could also be the option to have timer skeletons in the card that when bring enable, ask for an action.

If the timer countdown display will be handled via JS, this should also be integrated into the scheduler card.

**Comment by nielsfaber** [comment]
I agree this functionality is useful for HA.
However, it is fundamentally different to schedule things for a **duration** rather than on **time of day**.
Currently I don't see it realistic to combine both in the same card, it would require completely different UI for both setup and state display.
I also think the entities should derive from the [Timer](https://www.home-assistant.io/integrations/timer/) type.
The functionality behind these entities would impose significant changes to the integration (backend) as well, but possibly could be added to the scheduler integration (question mark).

I don't have the intention to spend effort on this.
But if someone has time and skill available to start with this, it would be great.
Parts of the code of this card may be re-used if it helps.

**Comment by Chaos02** [comment]
### Thank you, great!
Can this then maybe be labeled as something akin to "Open for pull request"?

**Comment by nielsfaber** [comment]
> Can this then maybe be labeled as something akin to "Open for pull request"?

I’m not open for pull requests for this feature, since I don’t believe it should be combined.
I think we are both agreeing on the need for a separate card for this. 
Which implies it needs its own repository, which perhaps could be branched from this one, depending on the preference of whoever might be willing to work on this.
I don’t know how to follow up on this request in this place.

**Comment by Chaos02** [comment]
ok, thanks! I'll consider learning HA programming then :P
