### ISSUE TITLE
Header toggler as a entity 

### ISSUE THREAD

**Issue by rVlad93** [nielsfaber/scheduler-card#573]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I would like this toggle button to be triggered using a service so I can disable all the schedules including the ones that will be created without adding them manually into the automation. 
![scheduler](https://user-images.githubusercontent.com/60452666/174877863-185c15c1-312e-4fc0-bde0-a760318d5ff9.jpg)

### Additional info

Either the component to generate a group that populates itself  or a scheduler.command that toggles that button.

**Comment by nielsfaber** [comment]
I'm sorry, but this is not possible.
This is because the button is part of the card, so it cannot be accessed outside of the card.
In case you have multiple cards, the card configuration determines which items show up in which card.
Perhaps you could make a script which loops through all schedule entities in HA and toggles them one by one?

**Comment by rVlad93** [comment]
Oh, got it. I'm not sure how to do that. The thing is I'm trying to disable the climate schedule when nobody is home and if any schedules where to be created as well. The person that's using this is pretty old so I can't bother them with adding conditions when they're creating a schedule. Any ideas where I should look?
