### ISSUE TITLE
Ability to pass parameters to services called by scheduler

### ISSUE THREAD

**Issue by p6sfrx725z28knfy** [nielsfaber/scheduler-card#586]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I would find it useful to be able to pass parameters or additional data to a service called by the scheduler-card actions, for example:

- #105 
- #115 
- #553 

Thanks

### Additional info

When creating a new schedule today you are asked to select GROUP, then ENTITY, then ACTION...

I would propose an additional step after selecting a supported action, such as Lights On/Off or Alarm Arm/Disarm, which allows the you to configure additional data or parameters in the same way as if you were calling the service directly.

I attempted to raise this as #556 but seems to have been ignored :(

**Comment by nielsfaber** [comment]
> I attempted to raise this as https://github.com/nielsfaber/scheduler-card/issues/556 but seems to have been ignored :(

Sorry. I am not very active with this project lately (holidays and such).

The best way to achieve what you're looking for is by customization of the card, effectively replacing the built-in actions of the card with your own versions.
You can add new actions with both fixed and user-configurable (i.e. textfield) service parameters.

In my opinion, the card should be kept as minimalistic as possible. For this reason I don't feel much for adding extra steps/fields in the card, since you're request is very use-case specific (I think 9/10 users don't want to color a light or arm/disarm an alarm on a timer.
