### ISSUE TITLE
Unable to connect to Home Assistant

### ISSUE THREAD

**Issue by brianhanifin** [nielsfaber/scheduler-card#59]
My Home Assistant UI has been shutting down with a simple Home Assistant logo and the message "Unable to connect to Home Assistant". I connect use it for a while, navigate around and eventually I try to open Home Assistant in a new tab, or click the browser refresh button and I am greeted with an impassible error message. I found that clearing my browser cache resolved it so I could login again, but it would come back. It was happening enough that I even installed a Firefox addon button "Clear private data now!" to make the recovery process quicker.

With my work-around... working, I hadn't done enough troubleshooting yet to track it down. Then I saw a user on Facebook posted about this issue. They later reported: *"So ... I restored a previous backup, went back to 0.114 and still had the issue. Once I removed a recently added integration 'scheduler card' it haven't encountered the issue since (testing for the past 40-50mins)"*

The problem I don't know how long it takes for this to occur, and it could take a while for it to manifest. I can tell you that it started occurring for me shortly before the Home Assistant 0.115 release. Though I can't be sure I believe it first occurred sometime in the last week. This was not occurring with your card before one of your recent updates.

Other info: I'm running Firefox on Windows 10.

![Screenshot 2020-09-22 074944](https://user-images.githubusercontent.com/57336/93898625-41fc9900-fca8-11ea-8208-d61ca652a4b2.png)

Facebook Home Assistant Group: [link to discussion](https://www.facebook.com/269300572/videos/860236579534/?extid=7WBZnWs7TuK4aw81)

**Comment by nielsfaber** [comment]
I heard about this from another user as well.
Ofcouse I take this very seriously.
Unfortunately I don't have a _clue_ what's going on here.
Which version of the card are you using?
Does it happen only when you try to login on the browser or app, or do automations also stop working?

**Comment by KTibow** [comment]
I had this same issue, once I moved to an external domain it was resolved.

**Comment by nielsfaber** [comment]
Which basically has the same effect as clearing your cache/cookies. I would expect it to come back eventually.

**Comment by KTibow** [comment]
Nope, haven't had the issue since.

**Comment by KTibow** [comment]
Welp. I just refreshed and it came back. It's still getting state updates pushed to it via websockets. Investigating...

**Comment by nielsfaber** [comment]
The only thing i can imagine is that could be related to my workaround for loading the card in the correct translation:
```
localStorage.setItem("selectedLanguage", hass.selectedLanguage);
```
The `localStorage` object is a sort of cache/cookie object, used by HA to store some of the frontend configurations.

**Comment by KTibow** [comment]
By the way, probably unrelated, but I see the loaded notice twice:
![image](https://user-images.githubusercontent.com/10727862/93914133-eee01180-fcba-11ea-9050-62730748d91e.png)

**Comment by KTibow** [comment]
And @nielsfaber couldn't you just get the correct language inside `localize.ts`?

**Comment by nielsfaber** [comment]
no, the method used in `localize` is not very good. Only is able to detect the language in case you changed your HA account language on that particular device. Because it reads the language from browser cache (`localStorage`).

**Comment by KTibow** [comment]
Could you make the code detect `hass.selectedLanguage` inside of `localize.ts`?

**Comment by nielsfaber** [comment]
No. Localize function is called everywhere where there is text. Hass object shouldn't be passed around that much.

**Comment by KTibow** [comment]
Get `hass` externally with `document.querySelector("home-assistant").hass`

**Comment by nielsfaber** [comment]
Yup. I think i will go that way. 
_Just in case_.
I really doubt it causes this frontend failures, but at this point i don't have any idea what does, so better to exclude `localStorage` from causing it.

**Comment by ASNNetworks** [comment]
I experienced this issue as well and created a ticket on Core. Other users had the exact same issue and pointed to the same Facebook post. Thank God someone saw that, cause I was going mental lol! 

I uninstalled everything (sadface) and havent’s had the issue in the last 12 hours. Now I see this ticket here as well, so I closed mine and mention this ticket. 

I LOVE your card and all the work. I hope you can get around this, so I can use it again :) 

Ironically, I was the one on the forum that stated the language didn’t work. Looks like the solution to that bit me in the ass lol!

**Comment by nielsfaber** [comment]
The new release [v1.4.0](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.4.0) removes the writes to `localStorage`.
I'm hoping someone can do a before-after test, to check whether it resolves anything.
I still did not see this problem myself, so I'm counting on you 👍

**Comment by ASNNetworks** [comment]
> The new release [v1.4.0](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.4.0) removes the writes to `localStorage`.
> I'm hoping someone can do a before-after test, to check whether it resolves anything.
> I still did not see this problem myself, so I'm counting on you 👍

Well, looks like I’m installing everything again! I pray to all the Gods the issues doesn’t come back (having trauma’s troubleshooting for 2 days straight). Gonna install now and keep you posted!

**Comment by nielsfaber** [comment]
> having trauma’s troubleshooting for 2 days straight

:flushed: :flushed: :flushed: Really hate to hear this!
I know the card is still buggy and all, but yeah, it's just a little after-hours project for me, so it takes time to get everything right.
But I had no idea that these kind of troubles could be caused by my card (or component).

Hoping to make it right with new fancy features 🦄

**Comment by ASNNetworks** [comment]
> > having trauma’s troubleshooting for 2 days straight
> 
> 😳 😳 😳 Really hate to hear this!
> I know the card is still buggy and all, but yeah, it's just a little after-hours project for me, so it takes time to get everything right.
> But I had no idea that these kind of troubles could be caused by my card (or component).
> 
> Hoping to make it right with new fancy features 🦄

Hey man, don't beat yourself up. I was just getting frustrated because my setup has been rock solid and looks/feels exactly like I wanted. And then that happened, so I was annoyed by the fact I couldn't find out as to why. Next time I know to look into custom components as well to troubleshoot :)

**Comment by ASNNetworks** [comment]
Oeh, I just had the error again btw!

**Comment by nielsfaber** [comment]
@ASNNetworks OK too bad. Could you try to remove the `scheduler-card` from your Lovelace config, keeping the scheduler integration running (with some (dummy) schedules)?  I would really like to know if it is caused by frontend or core.

**Comment by ASNNetworks** [comment]
> @ASNNetworks OK too bad. Could you try to remove the `scheduler-card` from your Lovelace config, keeping the scheduler integration running (with some (dummy) schedules)? I would really like to know if it is caused by frontend or core.

The issue happened without having schedules running/setup. I didn’t have any schedules setup yet. I have removed the card, but left the component and integration.

**Comment by nielsfaber** [comment]
@ASNNetworks component == integration ? There isn't really any difference as far as i know. Just to be clear 🙂

**Comment by ASNNetworks** [comment]
> @ASNNetworks component == integration ? There isn't really any difference as far as i know. Just to be clear 🙂

You need to install the component on HACS and after that through the integrations via HA. It is possible to only install the component through HACS, and ignore/forget adding the integration via HA settings. So they are separate technically. 

Component through HACS
![F6388E48-38B1-4F93-B32F-BF11D4B89307](https://user-images.githubusercontent.com/54230480/93931500-27b1d200-fd1f-11ea-97db-5b512e688274.jpeg)

Integration
![FC5281F5-8208-4280-B517-2DD80BF0B4D4](https://user-images.githubusercontent.com/54230480/93931545-3a2c0b80-fd1f-11ea-93e0-758f062b4b90.jpeg)

**Comment by nielsfaber** [comment]
@ASNNetworks You realize that HACS only copies files from my repo to your the `custom_components` folder right? 
Anyway, maybe i should have been more consistent with naming here 😅

**Comment by brianhanifin** [comment]
Sorry for the delayed reply. 

> Which version of the card are you using?

I have been updating all HACS updates quickly this week. I removed it last night, but I believe I was on the latest release.

> Does it happen only when you try to login on the browser or app, or do automations also stop working?

Personally, I have been working on my Home Automations for the past week like it is a 8 job 5 days a week. :)  So I've been all over the place. I understand you need to try to reproduce it. The two ways it would appear was:
1. Opening the site in a new tab.
2. Reloading the page with `Ctrl + R`
However:
* It would only occur after I had been using HA for a while.
* I was usually not interacting with the scheduler card. (My handful of schedules have been steady for a week or so.)
Other info:
* I use Lovelace UI Editor exclusively these days.
* Home Assistant 0.115.2
* Firefox 80.0.1
* Windows 10 19041.508
* HACS Frontend scripts installed:

```
lovelace-auto-entities/auto-entities.js
lovelace-badge-card/badge-card.js
button-card/button-card.js
lovelace-card-mod/card-mod.js
lovelace-card-tools/card-tools.js
check-button-card/check-button-card.js
custom-header/custom-header.js
favicon-counter/favicon-counter.js
lovelace-fold-entity-row/fold-entity-row.js
ha-card-weather-conditions/ha-card-weather-conditions.js
lovelace-home-feed-card/lovelace-home-feed-card.js
lovelace-text-input-row/lovelace-text-input-row.js
lovelace-multiple-entity-row/multiple-entity-row.js
mini-graph-card/mini-graph-card-bundle.js
lovelace-state-switch/state-switch.js
simple-thermostat/simple-thermostat.js
lovelace-slider-entity-row/slider-entity-row.js
weather-card/weather-card.js
lovelace-card-templater/lovelace-card-templater.js
lovelace-template-entity-row/template-entity-row.js
lovelace-gap-card/gap-card.js
restriction-card/restriction-card.js
atomic-calendar-revive/atomic-calendar-revive.js
```

**Comment by brianhanifin** [comment]
BTW, I haven't had any issues since I removed the scheduler-card, but I left the scheduler component running. I've been using Home Assistant all day, opened new tabs, reloaded pages repeatedly. I can't make it come back. I haven't tried the 1.4 version though.

**Comment by ASNNetworks** [comment]
Yes, I can confirm. Without the card there are no errors. Still having the component installed.

**Comment by nielsfaber** [comment]
@ASNNetworks thanks for confirming this. And you were using v1.4.0 right? 
Then I will investigate my code for potential vulnerabilities 🤓 

For my understanding: how are you able to trigger the problem?
Is it simply a matter of placing back the card in a Lovelace view, keeping a browser window open, and wait?
Or do you actively need to do stuff to trigger it? Keep F5-ing, or click through the GUI create schedules, stuff like this?
How often do you see it happening? 

I am looking for a beta tester who can help me to smash this bug, so I hope you can help by testing out a new version with potential fixes.
If it is caused by the card i can say with confidence that it will not be able to break your HA setup or anything. 
The card may contain a loop that keeps calculating stuff (this is what it seems like), but removing the card will shut it up completely.

**Comment by ASNNetworks** [comment]
> @ASNNetworks thanks for confirming this. And you were using v1.4.0 right?
> Then I will investigate my code for potential vulnerabilities 🤓
> 
> For my understanding: how are you able to trigger the problem?
> Is it simply a matter of placing back the card in a Lovelace view, keeping a browser window open, and wait?
> Or do you actively need to do stuff to trigger it? Keep F5-ing, or click through the GUI create schedules, stuff like this?
> How often do you see it happening?
> 
> I am looking for a beta tester who can help me to smash this bug, so I hope you can help by testing out a new version with potential fixes.
> If it is caused by the card i can say with confidence that it will not be able to break your HA setup or anything.
> The card may contain a loop that keeps calculating stuff (this is what it seems like), but removing the card will shut it up completely.

Yes, I was using v1.4.0 yesterday to test again and right after that one of my devices got the error. 

To trigger it, you need to either re-open the app or refresh the page. So basically, the content needs to be refreshed. That's why it's possible to have 2 Chrome windows open, while one is till fine and the other one shows the error after refresh. The other window will soon get the error after you refresh though. The only solution is clearing cache, which is possible on iOS HA app but not on Android. 

You can send me a PM if you want to beta test if that's easier for you. I am currently working (from home) but I'll try and test and respons as soon as possible. I don't expect the card to break stuff, but I have created a backup just to be safe.

**Comment by nielsfaber** [comment]
@brianhanifin  @ASNNetworks  @KTibow  @pqpxo 
Can you give an update of this problem?
Does the error still occur for you with the latest version of `scheduler-card`? How often?
Or did you completely stop using the scheduler?

Unfortunately, I am still unable to reproduce the problem. I am running HA with scheduler in 3 docker containers.
In the latest updates of the card I removed functionality that _could_ result in conflicts with the HA frontend, though none were likely to really cause these kind of problems.
As long as I don't know the root cause and cannot reproduce it myself, your experiences are very appreciated.

**Comment by ASNNetworks** [comment]
@nielsfaber Hi, I sent you a message on HA forum yesterday with an update. I think it’s fixed. With the latest update I haven’t seen the issue (yet). 

Though it did disconnect once on my tablet running Fully Kiosk a little time after I used the latest build, that could be because of cache. After that, the tablet hasn’t had an issue. My other devices haven’t had any issues at all.

**Comment by nielsfaber** [comment]
@ASNNetworks Thanks for the quick response. I did read your message, although I didn't respond to it, sorry about that.
The signals look good, hope it stays like that. Lets say: 'geen nieuws is goed nieuws' applies to you from now on 👍

But I don't cannot close this issue unless problems are solved for everyone. Therefore, i would like to collect feedback from all people who experienced the problem.
Also in the FB group I didn't see new updates on this, but it could also be that people simply gave up on the scheduler (which i wouldn't like to see ofcourse).

In the meantime i'm holding off from releasing new features, since i want the baseline to be stable first.

**Comment by ASNNetworks** [comment]
@nielsfaber I will update you tomorrow here, if there are still no issues, and no one else reports issues, I think we can say it’s officially fixed (right?). Has been over 72 hours then without issues.

**Comment by KTibow** [comment]
I'm using the latest version of the scheduler-card. Not happening recently, but I don't reload my page often if possible.

**Comment by brianhanifin** [comment]
0.115.3 included [an update to the frontend](https://github.com/home-assistant/core/pull/40549) which "Reverts lazy loading of more info control elements to give custom card developers more time to adapt/give them alternatives." I wondered if that might fix our problem so I reinstalled the card last night, and I haven't ran into the problem so far. I'll leave it installed and will report back if it returns.

**Comment by nielsfaber** [comment]
@brianhanifin The lazy loading was reverted after a discussion I had with Thomas Loven and Bram Kragten.
It was causing the slider and checkbox elements to disappear in the card.
They overlooked the (breaking) impact of their change on custom cards, and agreed that this needed to be reconsidered.
As a workaround there is a loader script implemented in v1.4.2 of this card (suggested by Thomas), which will trigger the loading of the slider+checkbox in the frontend. Hence the card will work also with lazy loading.

It was a nasty situation, but I doubt it was really the cause of the problems you had.
But i think the only way forward is to keep using the card and gain confidence that issues are resolved.

**Comment by ASNNetworks** [comment]
@nielsfaber I think it’s safe to say you have crushed the issues 🥳, running 96 hours without a single error.

**Comment by nielsfaber** [comment]
I close this issue, assuming that this problem is fixed with new version of the card.
Please re-open if there are problems again.
