### ISSUE TITLE
Missing temperature set point on thermostats

### ISSUE THREAD

**Issue by madasus** [nielsfaber/scheduler-card#618]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Expect to be able to set the thermostat temperature

### Actual behavior
Only have options for "Set Fan", "Set Mode" and "Turn Off"

### Steps to Reproduce

I have two different thermostats in my system (one from my OmniPro and one from Waterfurnace - both are coming in through MQTT)

![image](https://user-images.githubusercontent.com/9310056/197082850-6f1be93e-d67c-4e88-9cc0-5f028319fa2c.png)

The same device works fine with the thermostat card

![image](https://user-images.githubusercontent.com/9310056/197082980-f040b090-6302-4a87-81d3-1fbc1a924434.png)

Any idea why there is no option to set temperature set point?

**Comment by nielsfaber** [comment]
The problem is caused by the `supported_features` property.
This property is defined [here](https://developers.home-assistant.io/docs/core/entity/climate/#supported-features) and [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py#L163-L169) and used by scheduler-card to determine which actions the device supports.
The ability to set a temperature (heat or cool) will only show up in scheduler in case the `supported_features` contains 1 (i.e. `SUPPORT_TARGET_TEMPERATURE`). 

Your devices have supported_features 2+8=10 and 2+8+16=26. 
2 = `SUPPORT_TARGET_TEMPERATURE_RANGE`, i.e. regulating to a temperature range.
8 = `SUPPORT_FAN_MODE`, setting the fan mode
16 = `SUPPORT_PRESET_MODE`, setting a preset mode.

I think scheduler card has an error here, because it does not show up an action for regulating temperature. I will change this and let you know when this is done.

But I also see some problems with the implementation of this device:
* the `hvac_modes` property should contain `heat_cool` for supporting regulation between min/max limits (see [here](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes)).
* The `hvac_modes` `heat` (and `cool`) is shown, but the `supported_features` lacks `SUPPORT_TARGET_TEMPERATURE`, this is conflicting

These problems should be addressed by the maintainer of the device integration.

**Comment by nielsfaber** [comment]
Fix is on its way (https://github.com/nielsfaber/scheduler-card/commit/6fb07c1cad93b6cf44466d252c054178b2485738). 
I decided to remove all checks for `supported_features`, instead the actions are determined from the listed `hvac_modes`.
I will let you know when this change is released.

**Comment by madasus** [comment]
thanks - i'll do some testing once you are ready.

**Comment by madasus** [comment]
Hi,

I updated to the latest integration and card but when I select any of the thermostats I'm still not seeing an option to change the setpoint

![image](https://user-images.githubusercontent.com/9310056/202721823-c7aa07d4-fa7f-4b3a-9ad5-9f8bf6c4cbce.png)

M

**Comment by nielsfaber** [comment]
Hmm strange.
Could you do a simple check for me? If you edit an existing schedule and click 'delete', you will see a confirmation dialog.
Does the dialog show the normal text like this:
![image](https://user-images.githubusercontent.com/16861605/202792735-254dd7f4-68c3-40b4-8245-408d923fa62d.png)
If the text is missing something must have gone wrong with updating the card.

Otherwise we have to dig deeper into this problem. I thought I fixed this with the changes in the v2.3.8 release.

**Comment by lupin-de-mid** [comment]
I have same issue with  scheduler card 2.3.8   and  HA 2022.11.2
I'm able to control from thremostat card target temperature
 ```
hvac_modes:

  - 'off'
  - heat
min_temp: 15
max_temp: 40
target_temp_step: 0.5
current_temperature: 22.6
temperature: 25
friendly_name: Термостат Коридор
supported_features: 1
hvac_action: idle
```
![screen2](https://user-images.githubusercontent.com/986242/202850148-d13a4736-1957-4079-96f4-134231f4dd5a.png)

**Comment by nielsfaber** [comment]
@lupin-de-mid This issue is about the 'heat' action missing in the card for some entities. For you it is clearly visible, so I don't understand what you're saying.

**Comment by lupin-de-mid** [comment]
@nielsfaber  sorry if f'm wrong I could open another issue, if this is totaly different
But two points in this issue gave me assumption, that it has some relation to my issue
Issue topic is `Missing temperature set point on thermostats`
And  in  description i see this
```""Expected behavior

Expect to be able to set the thermostat temperature
```
And this is  my issue too.

**Comment by madasus** [comment]
@nielsfaber text is blank.  What is your suggestion to resolve?

![image](https://user-images.githubusercontent.com/9310056/202860655-5a493698-3e03-4c9c-97e3-8e35af9506da.png)

**Comment by nielsfaber** [comment]
@madasus Update the card via HACS (reinstall if needed). HACS should ask if you want to clear the cache (reload resources), you should do so. Otherwise you can clear your cache directly from the browser.

**Comment by madasus** [comment]
@nielsfaber removed the card completely and reinstalled  - still no text.

**Comment by lupin-de-mid** [comment]
Stil not working

**Comment by madasus** [comment]
it did start working for me.  Did you apply the last update?

**Comment by lupin-de-mid** [comment]
yes of course. and cleared browser cache

**Comment by madasus** [comment]
I'm seeing this correctly now - see here.  Are you seeing the extra boxes?

![image](https://user-images.githubusercontent.com/9310056/208688859-a08f3947-045a-4ef0-a03b-6600aed0b0b5.png)

**Comment by lupin-de-mid** [comment]
Did you mean  highlighted HEAT box?  that was missed on first image?

**Comment by madasus** [comment]
Correct - that was missing for me originally but now shows on all my stats.

**Comment by nielsfaber** [comment]
@lupin-de-mid 
Please check the version of the card that is currently running by opening the [browser log](https://help.zapier.com/hc/en-us/articles/8496199434765-View-and-save-your-browser-console-logs).

You should see a banner like this:
![image](https://user-images.githubusercontent.com/16861605/208734636-9cb47b5f-33ff-4790-9149-1d7591c70d4e.png)

I am not aware of any issues related to thermostats nor did I change anything about these in the last release.
If you do experience issues and you are on v2.4.0, please clarify what's wrong.
