### ISSUE TITLE
Update : custom element doesn't exist: scheduler-card

### ISSUE THREAD

**Issue by Dim3333** [nielsfaber/scheduler-card#624]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

latest

### Component Version

Latest version of HA

### Bug description

Hi,

After update to the last version,  the message displayed "custom element doesn't exist: scheduler-card" on my card.
Before the update, all was working.

Thanks for your help.

### Steps to reproduce

Nothing.

**Comment by nielsfaber** [comment]
Can you check if scheduler-card.js file is stored in the www/ folder?
If you use HACS it should be in www/community/scheduler-card/

**Comment by Dim3333** [comment]
It's strange, in the folder, i had only the zip file and not the js file. I don't why.
I unzipped the file and all works.

**Comment by maedball** [comment]
I had the exact same thing happening. Unpacking fixed it as well. Looks like HACS forgot to unzip it ;-)

**Comment by nielsfaber** [comment]
Since multiple users reported issues with upgrading to v2.3.8, I decided to make a new release v2.3.9 which doesn't have any changes but hopefully solves the updating via HACS.

**Comment by aal7** [comment]
Hello. I'm a bit late to the party on this one, because I've only just (very belatedly) done a load of updates, both to HA and HACS.
I too now have "custom element doesn't exist: scheduler-card".
As per above, I've checked my www/community/scheduler-card folder and there is a scheduler-card.js file in there.
I can see that this issue is marked fixed, but I can see the instructions about what I should do.
Could you spell it out, please?
Many thanks for your help.
