### ISSUE TITLE
Card is buggy cannot create a plan

### ISSUE THREAD

**Issue by cryd-s** [nielsfaber/scheduler-card#625]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

3.2.6

### Component Version

3.2.12

### Bug description

https://user-images.githubusercontent.com/47699362/202859837-f59fb812-e461-4754-b9e8-dbd95ef4f615.mp4

i think in the video u can see my problem i cannot add a time it deleted itself 

### Steps to reproduce

just want to create a scheduler for my heating

**Comment by nielsfaber** [comment]
Update the card to 2.3.8 please.
And make sure to clear your browser cache afterwards (in case HACS doesnt do this for you).
I think the update should solve your problems.

**Comment by cryd-s** [comment]
updated cache cleared but no fix

**Comment by glabbe0299** [comment]
I have the same problem, tried to uninstall reboot reinstall and still same problem every setting goes back to default when I try to change them.

**Comment by nielsfaber** [comment]
Please check your [browser console logs](https://help.zapier.com/hc/en-us/articles/8496199434765-View-and-save-your-browser-console-logs).
I'm not sure how to open it in Brave, but try ctrl+shift+i.
You should see a badge with the version of the card you're currently using:
![image](https://user-images.githubusercontent.com/16861605/202888411-926da0ac-ec42-432e-b983-137751397ef1.png)

Please share the results.
V2.3.8 is the latest version. V2.3.6 or lower has a known issue which may cause this, but it was fixed in v2.3.7 several months ago.

**Comment by splunkenizer** [comment]
I've got the same issues, having 2.3.6 installed. Unfortunately, I cannot update from HACS, because it shows the version as 3.2.6. Why is that?

**Comment by nielsfaber** [comment]
@cryd-s @glabbe0299 
Please let me know if all is solved now.
Otherwise, please follow https://github.com/nielsfaber/scheduler-card/issues/625#issuecomment-1321048194

**Comment by glabbe0299** [comment]
> @cryd-s @glabbe0299 Please let me know if all is solved now. Otherwise, please follow [#625 (comment)](https://github.com/nielsfaber/scheduler-card/issues/625#issuecomment-1321048194)

Clearing the cache did it for me thanks !
