### ISSUE TITLE
Custom element not found: scheduler-card

### ISSUE THREAD

**Issue by snoozer** [nielsfaber/scheduler-card#629]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.9

### Component Version

3,2,12

### Bug description

Installation does not work as explained.

### Steps to reproduce

Follow the installation instructions on Home Assistant OS 9.3 Core 2022.11.4

### Additional info

Hmmm..... I have been trying this for days now on a R-Pi as well as on a VM of Home Assistant. All works well to the point where I want to add the custom card. I use the copy button from the website here:

https://github.com/nielsfaber/scheduler-card#installation

juust to be sure I have no wrong whait spaces etc. I get the message:

Configuration errors detected: Custom element not found: scheduler-card

Also the documentation refers to a "ui-lovelace.yaml", I can not find that anywhere. I am stuck and don't know how to proceed. If I use the browser and point it to the file manually is is displayed in the browser. My URL is:

http://myip:8123/local/scheduler-card/scheduler-card.js?v=0

Help would be much appreciated
Kind Regards
Jan P.

PS: I forgot to mention, its Home Assistant OS 9.3 and Core 2022.11.4. I have also tried the HACS installation, that ends up in a different path but still does not work.  /root/config/www/community/scheduler-card instaed of /root/config/www/scheduler-card

**Comment by nielsfaber** [comment]
Make sure the js file of the card is in the www/ folder.
Next you need to register the card as an extra resource for the HA dashboard:
* if you manage your dashboard via yaml, the resources are in ui-lovelace.yaml
* If you manage your dashboard via UI (edit mode), you can go to configuration/dashboard and choose the tab resources. Note that this option only becomes available if you configured your user account as advanced or expert (not sure how it was called)

when you use HACS, adding the card to the resources is normally done for you.

last step is to clear the browser cache (or click reload resources in the dashboard editor 3 dots menu). This is really needed since HA uses extensive caching.

you could check your browser logs as well. There should be a message in case scheduler card is installed.

note that all of the above is not specific for this card, but applies to the installation of any custom card in HA. There are more extensive guides around..

**Comment by Th0masDB** [comment]
Hi, 

Today I got the same message. I used HACS for adding the card.
This are the logs from the browser:
![afbeelding](https://user-images.githubusercontent.com/12988955/204143788-641759ea-c3c0-4ffe-98d2-0043c8c5cdfb.png)

**Comment by rozrabiak** [comment]
The same for me, after installing via hacs - no sheduler card in lovelace.
/config/www/community/scheduler-card/scheduler-card.js - file exists
in lovelace/resources entry exists: /config/www/community/scheduler-card/scheduler-card.js
but i can't select card to add to dashboard - no card named scheduler.. :-(

**Comment by snoozer** [comment]
Hi nielsfaber,

I have installed the js file installed as per the instructions into www/scheduler-card. I have also registered the resource and browsing to the .js file showed me the content of said file. I do not have a file called ui-lovelace.yaml on my HA system as I stated in my 1st post.

Kind Regards
Jan P

**Comment by Ackmaniac** [comment]
> after second installation i have in lovelace this attention ![Zrzut ekranu 2022-11-28 212511](https://user-images.githubusercontent.com/73905882/204373995-cb0c2c2b-9ffc-4b1e-9c20-56eeacd72744.jpg)

having the same probem

**Comment by Breakingx** [comment]
Same problem here. I'm using the yaml mode. Downloaded the javascript via hacs. It automatically placed it here: www/community/scheduler-card/scheduler-card.js . After trying to import it into my yaml with: /hacsfiles/scheduler-card/scheduler-card.js the error occurs. Even with /local/scheduler-card/[...] . 

Is it possible to edit this card without the yaml? I think it's pretty uncomfortable to edit it in text.

**Comment by nielsfaber** [comment]
I wish to help but at this point I don't know how to.
@snoozer @Th0masDB 
> Configuration errors detected: Custom element not found: scheduler-card
Also the documentation refers to a "ui-lovelace.yaml", I can not find that anywhere. I am stuck and don't know how to proceed. If I use the browser and point it to the file manually is is displayed in the browser. My URL is:

This is still where you're stuck?
If you use HACS, I believe the registration in the resources is done automatically.
Otherwise you can follow the procedure here: https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/
If you use the ui-lovelace.yaml to manage your dashboard, you can see an example here: https://www.home-assistant.io/dashboards/dashboards/#adding-more-dashboards-with-yaml

@Th0masDB 
Please check if the scheduler-card.js is present in the www/ folder.
If you used HACS to download the card, i believe it should be in www/community/ instead.
After this, follow the instruction I gave to @snoozer for registering the card as resource. 

@rozrabiak  @Ackmaniac 
Please go to Settings -> Devices & Services in the HA menu.
Make sure there is a badge here for the scheduler component, e.g.:
<img src="https://user-images.githubusercontent.com/16861605/205148342-0438a260-4b68-4371-9f5a-28078173dd53.png" width="50%" height="50%">
If its not there, you didn't install the scheduler component (it has to be installed separately from the card).
You can use the big blue button in the bottom of the devices page to add it.
If it's not in this list, you didn't install the files of the custom_components. Start [here](https://github.com/nielsfaber/scheduler-component#installation).
If it fails to show up in the list after installing the files, clear the browser cache.

@Breakingx 
Which error exactly? Multiple problems are mentioned here.
Hope you can find your answer above.

**Comment by rozrabiak** [comment]
That's work's for me!
Thank's a lot! :-)

> @rozrabiak @Ackmaniac
> Please go to Settings -> Devices & Services in the HA menu.
> Make sure there is a badge here for the scheduler component, e.g.:
> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/16861605/205148342-0438a260-4b68-4371-9f5a-28078173dd53.png">
> If its not there, you didn't install the scheduler component (it has to be installed separately from the card).
> You can use the big blue button in the bottom of the devices page to add it.
> If it's not in this list, you didn't install the files of the custom_components. Start [here](https://github.com/nielsfaber/scheduler-component#installation).
> If it fails to show up in the list after installing the files, clear the browser cache.

**Comment by MaFel** [comment]
I had the same problems as rozrabiak. I wanted to install the scheduler card and it didn't work. It took me some hours to realize that I forgot to add Scheduler integration. I just saw you added it to the installation guide. For me it would been much easier to see if the ,,Note: Ensure to install https://github.com/nielsfaber/scheduler-component and add the integration in order for the scheduler to work properly." would be step 4 (install component) and 5(add integration) in the installation, because I didn't saw the difference between -card and -component and -integration in the first place...
But apart from this your Lovelace card is awesome, thanks for the nice work!

**Comment by Ackmaniac** [comment]
Thanks now it works
