### ISSUE TITLE
Allow setting Climate mode without changing temperature

### ISSUE THREAD

**Issue by Evanito** [nielsfaber/scheduler-card#647]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I already have an automation that changes the temperature of my generic thermostats, and the problem is this is overridden by using the Scheduler to turn on and off certain climates (ex: some are loud, so I turn them off when I have scheduled meetings)

I suggest the option for Schedules to turn on climates without needing to set a temp.

### Additional info

Please enjoy my artist's rendition :^) 
![image](https://user-images.githubusercontent.com/5620666/209281856-81e151f1-641e-46b8-9120-1627a2f80864.png)

I briefly checked the scheduler-component and it appears to me that it supports HVAC changes that do not include a temp change, so there may be no change required there.

**Comment by nielsfaber** [comment]
Since this is a very use-case specific request, I suggest you to define your own action to do this.
There are examples in the readme on how to add actions to the card (via yaml). In the bottom there’s an example on how to overwrite the default one.

I prefer not to change the built-in behaviour, since it may become more confusing for others.

**Comment by Evanito** [comment]
Sure, that works for me. Thanks

----------------------------------------

Dec 22, 2022 11:02:44 PM Niels Faber ***@***.***>:
