### ISSUE TITLE
Allow multiple entity types per schedule

### ISSUE THREAD

**Issue by nl0pvm** [nielsfaber/scheduler-card#652]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I would love to have the option of allowing multiple entity types per schedule. Although it could have the effect of making schedules look more complicated, the workaround of creating more of the same schedules per entity type is actually more complicated. 

Personally I have multiple lights, switches (that switch lights) and blinds that all follow the same schedule. As a result for a single scheduling moment I have three schedules.

### Additional info

For resolving the complexity I would suggest to colorize the entity types at the top in a different color in a way that it is clear that that entity type has entities selected.

**Comment by benjithompson** [comment]
Thanks for opening this. I was literally just about to open the SE thing. Many of my switches turn on lights, so being able to select entities from different "groups" (domains) would be very helpful. The workaround for this is using helpers to change the entity type of the switch to light, but I move my switches to different appliances occasionally so thos becomes tedious.

Another issue I found was when moving between the entity type tabs, it removes your previous selection.

**Comment by nl0pvm** [comment]
Please don't close this issue as it is still relevant.

**Comment by gajotnt** [comment]
Reopen please since i think i have the same issue.
Im trying to use two **select** entities but because they have diferent fields (it think thats whats causing it), it doenst allow me continue.

![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/ede84041-4dd4-451a-8c53-94a49d9fb4cf)

The options the selec entities have:
![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/7c6296c6-5326-45c7-976c-8e4b86e7ac6f)
![image](https://github.com/nielsfaber/scheduler-card/assets/25504364/102524a8-a3d2-4238-bf29-82b8c15c483f)
