### ISSUE TITLE
Allow omitting the year in the period

### ISSUE THREAD

**Issue by daufinsyd** [nielsfaber/scheduler-card#664]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

The card allow to select a period to run, however since it includes the year it has to be manually reconfigure each year (eg. automation running only in winter, or only in december/january ...).

It would be great to allow enter a period with days and month only, omitting the year.

### Additional info

Thank you for this amazing card, it's really gorgeous and pleasant to use !

**Comment by daufinsyd** [comment]
how can a feature request be staled ? :/

**Comment by nielsfaber** [comment]
@daufinsyd it is stale since no one (me included) stepped forward to implement this feature. I don’t want to keep all requests open since 9 out of 10 are very user specific and I have to prioritise what to spend my time on.

I agree your request can be useful. 
However this card uses a date picker that is part of HA (it’s also used for controlling the input_datetime helper for example).
As far as I know there is no possibility to modify it to omit the year.

I personally prefer to make it more generic by allowing users to place a wildcard (e.g. ‘*’) in either the day/month/year part to allow repeated patterns.
However as far as I can see there is no way to manually manipulate the date (only via the date picker dialog).

Note that this request also requires some modifications in the scheduler-component, but I see this much easier than the changes to the card.
