### ISSUE TITLE
Scheduler-card wrongly reported version

### ISSUE THREAD

**Issue by daha76** [nielsfaber/scheduler-card#675]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.7

### Component Version

v3.2.14

### Bug description

I updated Scheduler-card but in the browser console there is still version v2.4.1. I made browser cache clean, opening HA in the incognito mode, uninstall/reinstall of scheduler-card, different browser, ...  but the version is still v2.4.1 no matter what I have tried. But interestingly in the HACS I can see that I already have the latest version installed. Could it be that the reported version in the browser console is simply wrong?
![image](https://user-images.githubusercontent.com/16493975/219302476-11a12031-af0c-44a4-b4a6-6fcf7234824e.png)

### Steps to reproduce

Install latest version of scheduler-card
check version in the browser console

**Comment by nielsfaber** [comment]
You're right.
The v3.2.7 is a copy of v2.4.1. 
Since the source code of the card is not changed, it will (falsely) say v2.4.1 in the logs.
I only made a release with an increased version number, because for some users HACS was reporting they were on a higher (more recent) release than ever existed.
I should have updated the number in the source code as well, I'm sorry for not doing so.

**Comment by daha76** [comment]
Thanks for clarifying, no problem
