### ISSUE TITLE
feature request: holiday days binary sensor integration

### ISSUE THREAD

**Issue by GiladShoham** [nielsfaber/scheduler-card#71]
It will be great to have a feature to create a holiday day.
I think of something like this:
I have my own holiday binary sensor (based on many local integrations with some templates)
I'll configure the scheduler to look at this binary sensor.
then I can schedule stuff based on check whether it's a holiday or not. 
Will add a kind of checkbox to apply something only on holiday or only on not holiday.

**Comment by nielsfaber** [comment]
I am looking for a generic way to do this. One that will work for everyone.
In #27 the workday binary sensor is discussed.
The problem is that this sensor will only look at the current day.
The scheduler will need info for each day in the next week to be easily integrated.

Another way is to add condition checks before executing the action.
I think it is less elegant for this use-case, but also this is requested #24 .

I would like you to mention your wishes in the other issues.
This request is already covered by those.

**Comment by GiladShoham** [comment]
Sure will add my thoughts over there
