### ISSUE TITLE
One of two lights not turning off

### ISSUE THREAD

**Issue by mattfox27** [nielsfaber/scheduler-card#710]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

Latest 

### Bug description

I have 2 lights selected in my schedule and they are supposed to turn off 30min before sunset however randomly only one light turns off...It so wierd..this started happening after i restored an HA backup so im wondering if something is stuck somewhere?

### Steps to reproduce

light scheduled to turn off 30min before sunrise only one light turns off

**Comment by nielsfaber** [comment]
Please check the logbook (or history) of these lights.
Are you able to see that both lights were turned off at the scheduled time?

Otherwise, you could enable the debug logging for scheduler.

In the configuration.yaml add
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```

And restart HA afterwards.

When the schedule triggers you should see something like:

```
Timer 9514a0 has reached slot 0
Schedule 9514a0 is triggered, proceed with actions
Executing service light.turn_off on entity light.my_light_1
Executing service light.turn_off on entity light.my_light_2
```

I would expect the light_1 and light_2 to show up in the logging. If this is the case, scheduler does its job correctly, the issue is caused elsewhere.
I suspect that the integration which controls the light needs some time processing the first command, perhaps it ignores the second one if it comes too quickly.

Pleasse report back your findings.

**Comment by mattfox27** [comment]
Ya it's wierd I can see they turn on in the logs then only one will turn
off even though they are both set to turn off...yes let me turn on logging

**Comment by mattfox27** [comment]
Would the debug be in the home assistant log, just the regular amount one?

**Comment by nielsfaber** [comment]
Yes, the extra logging from scheduler will be added into the HA log.
