### ISSUE TITLE
Display ranges of picked values as secondary info

### ISSUE THREAD

**Issue by Nightenom** [nielsfaber/scheduler-card#713]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hi,
given schedule with scheme (for eg. switch) display ranges (for selected values - eg. switch "turn on") as secondary info

### Additional info

**source:**
![source](https://github.com/nielsfaber/scheduler-card/assets/17338378/b1505336-a3e4-4059-b7d0-b97e9d188a8c)

**now:**
![now](https://github.com/nielsfaber/scheduler-card/assets/17338378/ae29e434-1cf9-4bbb-993d-20e39ce37d42)

**wanted:**
![wanted](https://github.com/nielsfaber/scheduler-card/assets/17338378/ba9ee505-cdae-42d8-8783-fbd0e34fed0f)

**Comment by Nightenom** [comment]
Not stale

**Comment by nielsfaber** [comment]
As described in the [documentation](https://github.com/nielsfaber/scheduler-card#display-options), you can customize what is shown on the first line (bold text) and second line (or lines)
For example:
```yaml
display_options:
  primary_info: '{name}'
  secondary_info:
    - '{action} {time}'
```
Will give:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/63780e20-98ec-4a56-adc6-47f1451d2a05)

Which seems to match with your needs (except that you will see some capitalized letter at the beginning of the time description which may not be desired).

What is not possible, is to display grouped information of multiple timeslots. So showing `between 02:00-02:10 and 03:00-03:10` is not possible, it will only show the next timeslot, e.g. `02:00-02:10`.
This is done on purpose, the scheduler keeps no knowledge of tasks that are in the future, only the closest. I have no intentions to change this since it would require significant changes without much benefits.

**Comment by Nightenom** [comment]
Ok, understandable, thanks for config example, I will probably stick with default, this issue only? arise for night tasks where you can't see them changing
