### ISSUE TITLE
Climat bug

### ISSUE THREAD

**Issue by duczz** [nielsfaber/scheduler-card#718]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

Actuel stabile

### Component Version

Actuel stabile

### Bug description

The climate function works only when a Temperatur is setted, without No function, when i control it Manuel its working so its a bug
Can you fix These?

### Steps to reproduce

.

**Comment by nielsfaber** [comment]
I have no idea what you are talking about.
Please provide a clear description of the issue.

**Comment by duczz** [comment]
i try to explain the text in pictures, because i think its clearly :)

![image](https://github.com/nielsfaber/scheduler-card/assets/25475385/b1e4f4e4-600a-4239-b39a-b5a905296a8c)

**Comment by duczz** [comment]
the temperatur is default always setted, so it should be enough when i select only automatic in your scheduler (when i do this in the thermostat it works to), when i need to set a temperatur i have 2 different positions to change it completly
![image](https://github.com/nielsfaber/scheduler-card/assets/25475385/1fc73a5d-5f55-4afc-8251-2071783d7ef3)

**Comment by nielsfaber** [comment]
Due to lack of a proper description, your issue remains ignored so far.
Let's try again.

> The climate function works only when a Temperatur is setted without No function, when i control it 

Incorrect english, I don't understand the sentence.

>  Manuel its working so its a bug

I doubt it. What do you mean by manuel? What is not working?

> the temperatur is default always setted,

What is 'default'? What is 'setted'?

> so it should be enough when i select only automatic in your scheduler

I agree on this. If you leave the checkbox empty (unchecked), the scheduler will set your climate to 'automatic' mode without any temperature setting. This would mean the climate follows an internal program (behaviour depends on the device).

> when i need to set a temperatur i your scheduler i have 2 different positions to change it

What do you mean by 2 positions?
In your screenshots I only see 1 slider for setting the temperature.

**Comment by duczz** [comment]
i try my best, my english is not the best.

Im using this climate:
[![image](https://github.com/nielsfaber/scheduler-card/assets/25475385/6f871d89-cf99-4303-b4c0-ac8622c1a709)](https://user-images.githubusercontent.com/25475385/262618024-1fc73a5d-5f55-4afc-8251-2071783d7ef3.png)
there is already a setted temperature, this temperature should be taken in my opition when i dont set a temperature in your scheduler, because currently in my case the scheduler dont works when no temperature ist setted.
it would be create when i can use one temperature for all integrations which use this climate.

an other nice feature is when you add a time helper (optional) in your scheduler, than we no need always a extra schedulers for different day times, you know what i mean?
![image](https://github.com/nielsfaber/scheduler-card/assets/25475385/b6bb4d2a-063a-4a1f-abac-8741ed57f0d7)

**Comment by nielsfaber** [comment]
> there is already a setted temperature, this temperature should be taken in my opition when i dont set a temperature in your scheduler, because currently in my case the scheduler dont works when no temperature ist setted.

With the scheduler card you can set mode 'auto' without any temperature setting (by leaving the checkbox empty).
But modes 'heat' and 'cool' require a setpoint, since a vast majority of users which to heat to a certain temperature or cool to some other temperature (cooling to 23C does not have much practical use).

In case you only want to set the mode to 'cool' or 'heat' without any temperature, you can add an extra action for this to the card.

To do so, go to the YAML editor of the card:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/78a176d4-d6b4-4e03-b7a8-211423a657b7)

and add the `customize` section. For example:
```yaml
type: custom:scheduler-card
# your other settings should be here already, leave them
customize:
  climate.my_climate: # change for your own entity ID, or change to 'climate' to add the action to all climate entities
    actions:
      - name: Set mode to cool
        icon: snowflake
        service: climate.set_hvac_mode
        service_data:
          hvac_mode: cool # or heat
```
A new button will appear:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/8f8bd11f-3c25-4201-ad03-d74a8120fb7c)

**Comment by duczz** [comment]
Ah okay i understand, the customize Option ist good to know and exactly was i searched, thanks.
But when i use the Auto Mode without temperature nothing happens, only with setted temperature. (Currently tested)

What you think about the time helper?
