### ISSUE TITLE
Regression: temperature slider doesn't show value while changing

### ISSUE THREAD

**Issue by mjsambol** [nielsfaber/scheduler-card#821]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.13

### Component Version

3.3.3

### Bug description

As of a recent update, I can't see the temperature value as I adjust the slider in scheduler card. This makes it frustrating guesswork to hit a specific value. I've been using scheduler card for a long time and never saw this until just recently.

### Steps to reproduce

Try to set the temperature on a regular (not scheme) schedule entry.

**Comment by mjsambol** [comment]
Still relevant, though I see there's a 4.0.0 beta as of yesterday. Not feeling quite brave enough to try a beta for something so important!

**Comment by nielsfaber** [comment]
@mjsambol please try it. You can always roll back to the previous version.

**Comment by mjsambol** [comment]
I upgraded to 4.0.0b. This issue is unaffected - there is still no visual indicator of the value being selected while dragging a temp slider.

**Comment by nielsfaber** [comment]
@mjsambol could you share a screenshot of the issue you’re having? I don’t really understand, especially with the latest release. For me all looks like i expect it to.

**Comment by mjsambol** [comment]
![scheduler-card-screencap](https://github.com/user-attachments/assets/814c621a-7bf5-4289-8ecb-c6810bab6f6e)

It used to be the case that when adjusting the slider, the new value showed up in a bubble above the knob so that I could easily make fine-tuning adjustments, e.g. in this screenshot, move to 28.2. But that "bubble" is no longer. I only see the new value all the way at the right, once I release the slider. This makes it extremely difficult to adjust to a specific goal.

**Comment by mjsambol** [comment]
This image is from your documentation, showing the "bubble" I referred to above:
https://raw.githubusercontent.com/nielsfaber/scheduler-card/main/screenshots/action_variable_example.png?raw=true

**Comment by mjsambol** [comment]
I got back the display I wanted by rolling back to 3.2.10:
![scheduler-card-screencap-3 2 10](https://github.com/user-attachments/assets/80f6d72c-ea96-41d5-b708-ff9db28ffe33)

**Comment by mjsambol** [comment]
I see that in your release notes, 3.2.12 says
Updated sliders to be compatible with HA 2023.11 (thanks @devildant !)
and indeed, I am on HA 2023.10.3 / frontend 20231005.0
So I guess I need to first update HA, then update Scheduler-Card. Will be back...

**Comment by mjsambol** [comment]
I've upgraded HA to 2024.7.2 and Scheduler Card to 4.0.0.b0 and confirmed that I'm getting that version via developer tools console (and the red labels in the schedule UI)

First effect of this upgrade was to make all of my schedules disappear - I have them organized into 3 sections and now all three sections are empty except for a line reading "+ 43 excluded items".

Clicking that line to show the hidden schedules, they're all there, but many of the icons have changed - previously what was a thermometer is now a lightning bolt. The schedule names are also corrupted, lots of "null". See first attached image.

All of my schedules are now of the intervals
 kind, though they were not before. See second attached image.

This is basically a disaster for the setup, so I'm reverting and attaching images of what things look like on 3.2.13, though unfortunately with 3.2.13 I still 
lack the "bubble" that led me to open this issue in the first place.

![scheduler-card-beta-1](https://github.com/user-attachments/assets/2121ed35-2741-4620-ad81-983f8d621413)
![scheduler-card-beta-2](https://github.com/user-attachments/assets/58ea5fff-c9ef-46b9-9310-b98baeb52599)
![scheduler-card-3213-1](https://github.com/user-attachments/assets/f318a358-a6b0-4c95-a3ec-1000babc605b)
![scheduler-card-3213-2](https://github.com/user-attachments/assets/077a9bc2-6afa-45c4-9571-c8dd2290766b)

**Comment by nielsfaber** [comment]
@mjsambol 
Thanks for reporting your feedback.
Some of the issues you experience I also noticed (and partially fixed them already).
The issue with the time displaying as 'null' is new to me, I will take care of that.
> All of my schedules are now of the intervals kind, though they were not before. 

With the new version of the card the configured time will be always displayed on a bar (with the configured time below it). You can choose whether a scheduled task (slot) has an end time or not. It is just a visualization to get used to.

> This is basically a disaster for the setup

I understand your feeling.
On the other hand your testing helps me tackle some of the last issues that need to be addressed before it can be released to the public, thanks for that.
I don't think the result is that bad, no settings are lost, the issues are mainly visual and easy for me to fix.
It would be great if you could try out a next beta release as well, as your configuration (having 43 schedules) is a very good testing candidate.

> unfortunately with 3.2.13 I still lack the "bubble" that led me to open this issue in the first place.

I think you already found out yourself this is due to running an older HA version in combination with a version of scheduler-card which is adapted for newer HA version. So I think you should be able to resolve this issue by updating both. The slider shown in the card is a UI element defined from HA, likewise for the bubble.

**Comment by mjsambol** [comment]
Thanks @nielsfaber I appreciate your taking the feedback seriously. I am happy to continue trying out updates to 4.0.0 as it evolves.
